> **Corrección de firma:** esta revisión corrige la construcción de las firmas de configuración. Se usan `application` y `application_version` ya resueltos y las firmas se crean después de resolver `nodes`, `processes`, `ppn`, `filesystem`, `stripe_size_bytes`, `stripe_count` y `operation_mode`.

## Versión maestra acumulativa

Esta versión integra en un único proyecto:

- construcción dinámica de rutas por aplicación/campaña;
- adaptadores DLIO v1, DLIO actual y DeepGalaxy;
- firmas semánticas de aplicación, dataset y experimento;
- validación de ejecución, instrumentación y metadatos;
- extracción genérica de métricas científicas de aplicación;
- estado de cobertura de métricas: `AVAILABLE`, `PARTIAL`, `UNAVAILABLE`;
- salida `application_metrics_<clasificación>.csv`;
- soporte DeepGalaxy para `operation_mode=read` y métricas de entrenamiento.

# DeepTuneIO-Indexer v12

Versión genérica para indexar ejecuciones HPC de cualquier aplicación, con o sin Darshan.

Estados independientes:
- `execution_status`
- `instrumentation_status`
- `metadata_status`

Esta revisión conserva la **selección dinámica de aplicación/campaña** y añade la extracción genérica de **métricas científicas de la aplicación** mediante los adaptadores.

In [1]:
pwd

'F:\\NoteBooks\\CORA_DR_UAB\\Article_01_Parallel_IO_Analysis\\Scripts\\DeepTuneIO\\07_Indexer'

In [2]:
from pathlib import Path
import sys, json
import pandas as pd

# Carpeta que contiene el módulo principal y el paquete deeptuneio.
PROJECT_DIR = Path('./Module').resolve()

if str(PROJECT_DIR) not in sys.path:
    sys.path.insert(0, str(PROJECT_DIR))

from DeepTuneIO_Indexer_v12 import DeepTuneIOIndexer, write_outputs
from deeptuneio.adapters import AdapterRegistry

print('Proyecto:', PROJECT_DIR)
print('Módulo v10 disponible:', (PROJECT_DIR / 'DeepTuneIO_Indexer_v12.py').exists())

Proyecto: F:\NoteBooks\CORA_DR_UAB\Article_01_Parallel_IO_Analysis\Scripts\DeepTuneIO\07_Indexer\Module
Módulo v10 disponible: True

## 1. Seleccionar aplicación, dataset y escenario

La selección utiliza el mismo catálogo `CAMPAIGNS` y los mismos índices `APPLICATION_POS`, `DATASET_POS` y `SCENARIO_POS` empleados por los módulos DXT y Parser.

In [3]:
# ============================================================
# CONFIGURACIÓN GENERAL Y CATÁLOGO DE CAMPAÑAS
# ============================================================

RESOURCE_PROJECT = "RES-DATA-2022-1-0014"

PROJECT_ROOT = Path(r"F:\\NoteBooks\\CORA_DR_UAB").resolve()
ARTICLE_ID = "Article_01_Parallel_IO_Analysis"
ARTICLE_ROOT = PROJECT_ROOT / ARTICLE_ID

# Catálogo común con los módulos de procesamiento.
CAMPAIGNS = {
    "DeepGalaxy": {
        "DG_bw512_f3c5x64": {
            "scenarios": [
                "lustre_1ost",
                "lustre_2ost",
                "lustre_4ost",
                "nfs_SnGPU_e1",
            ],
            "file_format": ".hdf5",
        },
    },
    "DLIOv1": {
        "HDF5_64bs": {
            "scenarios": ["lustre_ost"],
            "file_format": ".h5",
        },
        "NPZ_64bs": {
            "scenarios": ["lustre_ost"],
            "file_format": ".npz",
        },
        "TFRecord_256kts_64bs": {
            "scenarios": ["lustre_ost"],
            "file_format": ".tfrecords",
        },
        "TFRecord_1mts_64bs": {
            "scenarios": ["lustre_ost"],
            "file_format": ".tfrecords",
        },
    },
}

# ------------------------------------------------------------
# Cambiar únicamente estos índices para seleccionar otra campaña.
# Los índices empiezan en 1, igual que en Module 06 y Module 07.
# ------------------------------------------------------------
APPLICATION_POS = 1
DATASET_POS = 1
SCENARIO_POS = 1

APPLICATION_OPTIONS = list(CAMPAIGNS)
if not 1 <= APPLICATION_POS <= len(APPLICATION_OPTIONS):
    raise ValueError("APPLICATION_POS fuera de rango.")
APPLICATION = APPLICATION_OPTIONS[APPLICATION_POS - 1]

DATASET_OPTIONS = list(CAMPAIGNS[APPLICATION])
if not 1 <= DATASET_POS <= len(DATASET_OPTIONS):
    raise ValueError("DATASET_POS fuera de rango.")
DATASET_GROUP = DATASET_OPTIONS[DATASET_POS - 1]

SCENARIO_OPTIONS = CAMPAIGNS[APPLICATION][DATASET_GROUP]["scenarios"]
if not 1 <= SCENARIO_POS <= len(SCENARIO_OPTIONS):
    raise ValueError("SCENARIO_POS fuera de rango.")
SCENARIO = SCENARIO_OPTIONS[SCENARIO_POS - 1]

FILE_FORMAT = CAMPAIGNS[APPLICATION][DATASET_GROUP]["file_format"]

print("Project root  :", PROJECT_ROOT)
print("Article root  :", ARTICLE_ROOT)
print("Application   :", APPLICATION)
print("Dataset group :", DATASET_GROUP)
print("Scenario      :", SCENARIO)
print("File format   :", FILE_FORMAT)

Project root  : F:\NoteBooks\CORA_DR_UAB
Article root  : F:\NoteBooks\CORA_DR_UAB\Article_01_Parallel_IO_Analysis
Application   : DeepGalaxy
Dataset group : DG_bw512_f3c5x64
Scenario      : lustre_1ost
File format   : .hdf5

## 2. Construir la raíz de la campaña

La ruta sigue la jerarquía común de DeepTuneIO:

`<PROJECT_ROOT>/<ARTICLE_ID>/Data/<APPLICATION>/<DATASET_GROUP>/<SCENARIO>/`.

In [4]:
# ============================================================
# CONSTRUCCIÓN UNIFICADA DE LA RUTA DE CAMPAÑA
# ============================================================

CAMPAIGN_ROOT = (
    ARTICLE_ROOT
    / "Data"
    / APPLICATION
    / DATASET_GROUP
    / SCENARIO
).resolve()

# El Indexer examina recursivamente la campaña completa porque sus fuentes
# pueden encontrarse en diferentes subdirectorios:
#   - Slurm stdout/stderr
#   - SEFF
#   - Darshan Parser
#   - Darshan DXT
#   - Darshan PERF
INPUT_DIR = CAMPAIGN_ROOT

# Las salidas del Indexer se mantienen separadas de las fuentes y de los
# resultados científicos de Parser/DXT/PERF.
OUTPUT_DIR = CAMPAIGN_ROOT / "results" / "Indexer"

print("Campaign root :", CAMPAIGN_ROOT)
print("Input dir     :", INPUT_DIR)
print("Output dir    :", OUTPUT_DIR)
print("Campaign exists:", CAMPAIGN_ROOT.exists())

if not CAMPAIGN_ROOT.exists():
    raise FileNotFoundError(
        f"No existe la campaña seleccionada: {CAMPAIGN_ROOT}"
    )

Campaign root : F:\NoteBooks\CORA_DR_UAB\Article_01_Parallel_IO_Analysis\Data\DeepGalaxy\DG_bw512_f3c5x64\Lustre_1ost
Input dir     : F:\NoteBooks\CORA_DR_UAB\Article_01_Parallel_IO_Analysis\Data\DeepGalaxy\DG_bw512_f3c5x64\Lustre_1ost
Output dir    : F:\NoteBooks\CORA_DR_UAB\Article_01_Parallel_IO_Analysis\Data\DeepGalaxy\DG_bw512_f3c5x64\Lustre_1ost\results\Indexer
Campaign exists: True

In [5]:
# ============================================================
# INSPECCIÓN DE FUENTES DISPONIBLES EN LA CAMPAÑA
# ============================================================

# Esta celda no impone una ubicación física concreta para cada evidencia.
# Solo comprueba, de forma recursiva, qué fuentes puede encontrar el Indexer.

def count_matching(root: Path, predicate):
    return sum(1 for p in root.rglob("*") if p.is_file() and predicate(p))

source_counts = {
    "stdout (.out)": count_matching(INPUT_DIR, lambda p: p.suffix.lower() == ".out"),
    "stderr (.err)": count_matching(INPUT_DIR, lambda p: p.suffix.lower() == ".err"),
    "SEFF txt": count_matching(
        INPUT_DIR,
        lambda p: p.suffix.lower() == ".txt" and "seff" in p.name.lower()
    ),
    "Parser txt": count_matching(
        INPUT_DIR,
        lambda p: p.suffix.lower() == ".txt" and "parser" in p.name.lower()
    ),
    "DXT txt": count_matching(
        INPUT_DIR,
        lambda p: p.suffix.lower() == ".txt" and "_dxt" in p.name.lower()
    ),
    "PERF txt": count_matching(
        INPUT_DIR,
        lambda p: p.suffix.lower() == ".txt" and "_perf" in p.name.lower()
    ),
}

for source, count in source_counts.items():
    print(f"{source:15s}: {count}")

stdout (.out)  : 39
stderr (.err)  : 39
SEFF txt       : 39
Parser txt     : 39
DXT txt        : 39
PERF txt       : 39

## 2. Construir índice

## Resultados de entrenamiento

La v12 conserva la serie completa en `application_metrics_*.csv` y añade `training_summary_*.csv`, con una fila por JobID validado. Este resumen incluye estado de entrenamiento, épocas esperadas/completadas, métricas finales y los mínimos/máximos de `loss`, `validation_loss`, `accuracy` y `validation_accuracy` cuando la aplicación los expone mediante su adaptador.

In [6]:
indexer = DeepTuneIOIndexer(resource_project=RESOURCE_PROJECT)
records, issues = indexer.run(INPUT_DIR)
outputs = write_outputs(records, issues, OUTPUT_DIR)

print(f'Experimentos indexados: {len(records)}')
for name, path in outputs.items():
    print(f'{name}: {path.resolve()}')

Experimentos indexados: 39
csv: F:\NoteBooks\CORA_DR_UAB\Article_01_Parallel_IO_Analysis\Data\DeepGalaxy\DG_bw512_f3c5x64\Lustre_1ost\results\Indexer\experiment_index_hdf5.csv
incomplete_csv: F:\NoteBooks\CORA_DR_UAB\Article_01_Parallel_IO_Analysis\Data\DeepGalaxy\DG_bw512_f3c5x64\Lustre_1ost\results\Indexer\incomplete_experiments_hdf5.csv
json: F:\NoteBooks\CORA_DR_UAB\Article_01_Parallel_IO_Analysis\Data\DeepGalaxy\DG_bw512_f3c5x64\Lustre_1ost\results\Indexer\experiment_index_master_hdf5.json
validation_report: F:\NoteBooks\CORA_DR_UAB\Article_01_Parallel_IO_Analysis\Data\DeepGalaxy\DG_bw512_f3c5x64\Lustre_1ost\results\Indexer\validation_report_hdf5.txt
experiment_matrix: F:\NoteBooks\CORA_DR_UAB\Article_01_Parallel_IO_Analysis\Data\DeepGalaxy\DG_bw512_f3c5x64\Lustre_1ost\results\Indexer\experiment_matrix_hdf5.csv
campaign_coverage: F:\NoteBooks\CORA_DR_UAB\Article_01_Parallel_IO_Analysis\Data\DeepGalaxy\DG_bw512_f3c5x64\Lustre_1ost\results\Indexer\campaign_coverage_hdf5.json
application_metrics: F:\NoteBooks\CORA_DR_UAB\Article_01_Parallel_IO_Analysis\Data\DeepGalaxy\DG_bw512_f3c5x64\Lustre_1ost\results\Indexer\application_metrics_hdf5.csv
training_summary: F:\NoteBooks\CORA_DR_UAB\Article_01_Parallel_IO_Analysis\Data\DeepGalaxy\DG_bw512_f3c5x64\Lustre_1ost\results\Indexer\training_summary_hdf5.csv

## 3. Inspeccionar resultados

In [6]:
df = pd.read_csv(outputs['csv'])
df

,experiment_id,sequence_id,application,application_version,application_version_source,application_version_confidence,configuration_source,job_id,platform,resource_project,...,perf_file,seff_file,stdout_file,stderr_file,paper_figures,paper_tables,execution_status,instrumentation_status,metadata_status,validation_notes
0,DTIO_4935078,1,DeepGalaxy,legacy,dg_train_cli_signature,HIGH,deepgalaxy_cli,4935078,FinisTerrae III,RES-DATA-2022-1-0014,...,Perf\1_DG_N1p4e1_EfficientNetB4_outputbw512hdf...,Seff\1_DeepGalaxy_lustre_1ost_bw512_4935078_hd...,Slurm\1_DG_L1ost_e1_4935078.out,Slurm\1_DG_L1ost_e1_4935078.err,NaN,NaN,PASS,COMPLETE,PASS,[INFO] stderr: 2 warning-like messages detected.
1,DTIO_4969259,21,DeepGalaxy,legacy,dg_train_cli_signature,HIGH,deepgalaxy_cli,4969259,FinisTerrae III,RES-DATA-2022-1-0014,...,Perf\21_DG_N1p4e1_EfficientNetB4_outputbw512hd...,Seff\21_DG_L1ost_bw512_4969259_hdf5_seff_JSC24...,Slurm\21_DG_L1ost_e1_4969259.out,Slurm\21_DG_L1ost_e1_4969259.err,NaN,NaN,PASS,COMPLETE,PASS,[INFO] stderr: 2 warning-like messages detected.
2,DTIO_4998171,7,DeepGalaxy,legacy,dg_train_cli_signature,HIGH,deepgalaxy_cli,4998171,FinisTerrae III,RES-DATA-2022-1-0014,...,Perf\7_DG_N2p8e1_EfficientNetB4_outputbw512hdf...,Seff\7_DeepGalaxy_lustre_1ost_bw512_4998171_hd...,Slurm\7_DG_L1ost_e1_4998171.out,Slurm\7_DG_L1ost_e1_4998171.err,NaN,NaN,PASS,COMPLETE,PASS,[INFO] stderr: 2 warning-like messages detected.
3,DTIO_5004132,27,DeepGalaxy,legacy,dg_train_cli_signature,HIGH,deepgalaxy_cli,5004132,FinisTerrae III,RES-DATA-2022-1-0014,...,Perf\27_DG_N4p16e1_EfficientNetB4_outputbw512h...,Seff\27_DeepGalaxy_lustre_1ost_bw512_5004132_h...,Slurm\27_DG_L1ost_e1_5004132.out,Slurm\27_DG_L1ost_e1_5004132.err,NaN,NaN,PASS,COMPLETE,PASS,[INFO] stderr: 2 warning-like messages detected.
4,DTIO_5005753,31,DeepGalaxy,legacy,dg_train_cli_signature,HIGH,deepgalaxy_cli,5005753,FinisTerrae III,RES-DATA-2022-1-0014,...,Perf\31_DG_N8p32e1_EfficientNetB4_outputbw512h...,Seff\31_DeepGalaxy_lustre_1ost_bw512_5005753_h...,Slurm\31_DG_L1ost_e1_5005753.out,Slurm\31_DG_L1ost_e1_5005753.err,NaN,NaN,PASS,COMPLETE,PASS,[INFO] stderr: 2 warning-like messages detected.
5,DTIO_5006747,35,DeepGalaxy,legacy,dg_train_cli_signature,HIGH,deepgalaxy_cli,5006747,FinisTerrae III,RES-DATA-2022-1-0014,...,Perf\35_DG_N12p48e1_EfficientNetB4_outputbw512...,Seff\35_DeepGalaxy_lustre_1ost_bw512_5006747_h...,Slurm\35_DG_L1ost_e1_5006747.out,Slurm\35_DG_L1ost_e1_5006747.err,NaN,NaN,PASS,COMPLETE,PASS,[INFO] stderr: 2 warning-like messages detected.
6,DTIO_5136097,24,DeepGalaxy,legacy,dg_train_cli_signature,HIGH,deepgalaxy_cli,5136097,FinisTerrae III,RES-DATA-2022-1-0014,...,Perf\24_DG_N2p8e1_EfficientNetB4_outputbw512hd...,Seff\24_DG_L1ost_bw512_5136097_hdf5_seff_JSC24...,Slurm\24_DG_L1ost_e1_5136097.out,Slurm\24_DG_L1ost_e1_5136097.err,NaN,NaN,PASS,COMPLETE,PASS,[INFO] stderr: 2 warning-like messages detected.
7,DTIO_5145754,25,DeepGalaxy,legacy,dg_train_cli_signature,HIGH,deepgalaxy_cli,5145754,FinisTerrae III,RES-DATA-2022-1-0014,...,Perf\25_DG_N2p8e1_EfficientNetB4_outputbw512hd...,Seff\25_DeepGalaxy_lustre_1ost_bw512_5145754_h...,Slurm\25_DG_L1ost_e1_5145754.out,Slurm\25_DG_L1ost_e1_5145754.err,NaN,NaN,PASS,COMPLETE,PASS,[INFO] stderr: 2 warning-like messages detected.
8,DTIO_5147852,4,DeepGalaxy,legacy,dg_train_cli_signature,HIGH,deepgalaxy_cli,5147852,FinisTerrae III,RES-DATA-2022-1-0014,...,Perf\4_DG_N2p8e1_EfficientNetB4_outputbw512hdf...,Seff\4_DeepGalaxy_lustre_1ost_bw512_5147852_hd...,Slurm\4_DG_L1ost_e1_5147852.out,Slurm\4_DG_L1ost_e1_5147852.err,NaN,NaN,PASS,COMPLETE,PASS,[INFO] stderr: 2 warning-like messages detected.
9,DTIO_5164453,5,DeepGalaxy,legacy,dg_train_cli_signature,HIGH,deepgalaxy_cli,5164453,FinisTerrae III,RES-DATA-2022-1-0014,...,Perf\5_DG_N2p8e1_EfficientNetB4_outputbw512hdf...,Seff\5_DeepGalaxy_lustre_1ost_bw512_5164453_hd...,Slurm\5_DG_L1ost_e1_5164453.out,Slurm\5_DG_L1ost_e1_5164453.err,NaN,NaN,PASS,COMPLETE,PASS,[INFO] stderr: 2 warning-like messages detected.
10,DTIO_5171929,15,DeepGalaxy,legacy,dg_train_cli_signature,HIGH,deepgalaxy_cli,5171929,FinisTerrae III,RES-DATA-2022-1-0014,...,Perf\15_DG_N12p48e1_EfficientNetB4_outputbw512...,Seff\15_DeepGalaxy_lustre_1ost_bw512_5171929_h...,Slurm\15_DG_L1ost_e1_5171929.out,Slurm\15_DG_L1ost_e1_5171929.err,NaN,NaN,PASS,COMPLETE,PASS,[INFO] stderr: 2 warning-like messages detected.
11,DTIO_5172393,16,DeepGalaxy,legacy,dg_train_cli_signature,HIGH,deepgalaxy_cli,5172393,FinisTerrae III,RES-DATA-2022-1-0014,...,Perf\16_DG_N12p48e1_EfficientNetB4_outputbw512...,Seff\16_DeepGalaxy_lustre_1ost_bw512_5172393_h...,Slurm\16_DG_L1ost_e1_5172393.out,Slurm\16_DG_L1ost_e1_5172393.err,NaN,NaN,PASS,COMPLETE,PASS,[INFO] stderr: 2 warning-like messages detected.
12,DTIO_5173520,36,DeepGalaxy,legacy,dg_train_cli_signature,HIGH,deepgalaxy_cli,5173520,FinisTerrae III,RES-DATA-2022-1-0014,...,Perf\36_DG_N12p48e1_EfficientNetB4_outputbw512...,Seff\36_DeepGalaxy_lustre_1ost_bw512_5173520_h...,Slurm\36_DG_L1ost_e1_5173520.out,Slurm\36_DG_L1ost_e1_5173520.err,NaN,NaN,PASS,COMPLETE,PASS,[INFO] stderr: 2 warning-like messages detected.
13,DTIO_5178759,11,DeepGalaxy,legacy,dg_train_cli_signature,HIGH,deepgalaxy_cli,5178759,FinisTerrae III,RES-DATA-2022-1-0014,...,Perf\11_DG_N8p32e1_EfficientNetB4_outputbw512h...,Seff\11_DG_L1ost_bw512_5178759_hdf5_seff_JSC24...,Slurm\11_DG_L1ost_e1_5178759.out,Slurm\11_DG_L1ost_e1_5178759.err,NaN,NaN,PASS,COMPLETE,PASS,[INFO] stderr: 2 warning-like messages detected.
14,DTIO_5181608,12,DeepGalaxy,legacy,dg_train_cli_signature,HIGH,deepgalaxy_cli,5181608,FinisTerrae III,RES-DATA-2022-1-0014,...,Perf\12_DG_N8p32e1_EfficientNetB4_outputbw512h...,Seff\12_DG_L1ost_bw512_5181608_hdf5_seff_JSC24...,Slurm\12_DG_L1ost_e1_5181608.out,Slurm\12_DG_L1ost_e1_5181608.err,NaN,NaN,PASS,COMPLETE,PASS,[INFO] stderr: 2 warning-like messages detected.
15,DTIO_5182586,32,DeepGalaxy,legacy,dg_train_cli_signature,HIGH,deepgalaxy_cli,5182586,FinisTerrae III,RES-DATA-2022-1-0014,...,Perf\32_DG_N8p32e1_EfficientNetB4_outputbw512h...,Seff\32_DeepGalaxy_lustre_1ost_bw512_5182586_h...,Slurm\32_DG_L1ost_e1_5182586.out,Slurm\32_DG_L1ost_e1_5182586.err,NaN,NaN,PASS,COMPLETE,PASS,[INFO] stderr: 2 warning-like messages detected.
16,DTIO_5183430,33,DeepGalaxy,legacy,dg_train_cli_signature,HIGH,deepgalaxy_cli,5183430,FinisTerrae III,RES-DATA-2022-1-0014,...,Perf\33_DG_N8p32e1_EfficientNetB4_outputbw512h...,Seff\33_DeepGalaxy_lustre_1ost_bw512_5183430_h...,Slurm\33_DG_L1ost_e1_5183430.out,Slurm\33_DG_L1ost_e1_5183430.err,NaN,NaN,PASS,COMPLETE,PASS,[INFO] stderr: 2 warning-like messages detected.
17,DTIO_5184753,8,DeepGalaxy,legacy,dg_train_cli_signature,HIGH,deepgalaxy_cli,5184753,FinisTerrae III,RES-DATA-2022-1-0014,...,Perf\8_DG_N4p16e1_EfficientNetB4_outputbw512hd...,Seff\8_DeepGalaxy_lustre_1ost_bw512_5184753_hd...,Slurm\8_DG_L1ost_e1_5184753.out,Slurm\8_DG_L1ost_e1_5184753.err,NaN,NaN,PASS,COMPLETE,PASS,[INFO] stderr: 2 warning-like messages detected.
18,DTIO_5185397,28,DeepGalaxy,legacy,dg_train_cli_signature,HIGH,deepgalaxy_cli,5185397,FinisTerrae III,RES-DATA-2022-1-0014,...,Perf\28_DG_N4p16e1_EfficientNetB4_outputbw512h...,Seff\28_DeepGalaxy_lustre_1ost_bw512_5185397_h...,Slurm\28_DG_L1ost_e1_5185397.out,Slurm\28_DG_L1ost_e1_5185397.err,NaN,NaN,PASS,COMPLETE,PASS,[INFO] stderr: 2 warning-like messages detected.
19,DTIO_5186976,22,DeepGalaxy,legacy,dg_train_cli_signature,HIGH,deepgalaxy_cli,5186976,FinisTerrae III,RES-DATA-2022-1-0014,...,Perf\22_DG_N1p4e1_EfficientNetB4_outputbw512hd...,Seff\22_DeepGalaxy_lustre_1ost_bw512_5186976_h...,Slurm\22_DG_L1ost_e1_5186976.out,Slurm\22_DG_L1ost_e1_5186976.err,NaN,NaN,PASS,COMPLETE,PASS,[INFO] stderr: 2 warning-like messages detected.
20,DTIO_5189973,30,DeepGalaxy,legacy,dg_train_cli_signature,HIGH,deepgalaxy_cli,5189973,FinisTerrae III,RES-DATA-2022-1-0014,...,Perf\30_DG_N4p16e1_EfficientNetB4_outputbw512h...,Seff\30_DeepGalaxy_lustre_1ost_bw512_5189973_h...,Slurm\30_DG_L1ost_e1_5189973.out,Slurm\30_DG_L1ost_e1_5189973.err,NaN,NaN,PASS,COMPLETE,PASS,[INFO] stderr: 2 warning-like messages detected.
21,DTIO_5196039,2,DeepGalaxy,legacy,dg_train_cli_signature,HIGH,deepgalaxy_cli,5196039,FinisTerrae III,RES-DATA-2022-1-0014,...,Perf\2_DG_N1p4e1_EfficientNetB4_outputbw512hdf...,Seff\2_DeepGalaxy_lustre_1ost_bw512_5196039_hd...,Slurm\2_DG_L1ost_e1_5196039.out,Slurm\2_DG_L1ost_e1_5196039.err,NaN,NaN,PASS,COMPLETE,PASS,[INFO] stderr: 2 warning-like messages detected.
22,DTIO_5317272,23,DeepGalaxy,legacy,dg_train_cli_signature,HIGH,deepgalaxy_cli,5317272,FinisTerrae III,RES-DATA-2022-1-0014,...,Perf\23_DG_N1p4e1_EfficientNetB4_outputbw512hd...,Seff\23_DeepGalaxy_lustre_1ost_bw512_5317272_h...,Slurm\23_DG_L1ost_e1_5317272.out,Slurm\23_DG_L1ost_e1_5317272.err,NaN,NaN,PASS,COMPLETE,PASS,[INFO] stderr: 2 warning-like messages detected.
23,DTIO_5333215,18,DeepGalaxy,legacy,dg_train_cli_signature,HIGH,deepgalaxy_cli,5333215,FinisTerrae III,RES-DATA-2022-1-0014,...,Perf\18_DG_N16p64e1_EfficientNetB4_outputbw512...,Seff\18_DeepGalaxy_lustre_1ost_bw512_5333215_h...,Slurm\18_DG_L1ost_e1_5333215.out,Slurm\18_DG_L1ost_e1_5333215.err,NaN,NaN,PASS,COMPLETE,PASS,[INFO] stderr: 2 warning-like messages detected.
24,DTIO_5347797,37,DeepGalaxy,legacy,dg_train_cli_signature,HIGH,deepgalaxy_cli,5347797,FinisTerrae III,RES-DATA-2022-1-0014,...,Perf\37_DG_N12p48e1_EfficientNetB4_outputbw512...,Seff\37_DeepGalaxy_lustre_1ost_bw512_5347797_h...,Slurm\37_DG_L1ost_e1_5347797.out,Slurm\37_DG_L1ost_e1_5347797.err,NaN,NaN,PASS,COMPLETE,PASS,[INFO] stderr: 2 warning-like messages detected.
25,DTIO_5348184,34,DeepGalaxy,legacy,dg_train_cli_signature,HIGH,deepgalaxy_cli,5348184,FinisTerrae III,RES-DATA-2022-1-0014,...,Perf\34_DG_N8p32e1_EfficientNetB4_outputbw512h...,Seff\34_DeepGalaxy_lustre_1ost_bw512_5348184_h...,Slurm\34_DG_L1ost_e1_5348184.out,Slurm\34_DG_L1ost_e1_5348184.err,NaN,NaN,PASS,COMPLETE,PASS,[INFO] stderr: 2 warning-like messages detected.
26,DTIO_5349515,13,DeepGalaxy,legacy,dg_train_cli_signature,HIGH,deepgalaxy_cli,5349515,FinisTerrae III,RES-DATA-2022-1-0014,...,Perf\13_DG_N8p32e1_EfficientNetB4_outputbw512h...,Seff\13_DG_L1ost_bw512_5349515_hdf5_seff_JSC24...,Slurm\13_DG_L1ost_e1_5349515.out,Slurm\13_DG_L1ost_e1_5349515.err,NaN,NaN,PASS,COMPLETE,PASS,[INFO] stderr: 2 warning-like messages detected.
27,DTIO_5350177,3,DeepGalaxy,legacy,dg_train_cli_signature,HIGH,deepgalaxy_cli,5350177,FinisTerrae III,RES-DATA-2022-1-0014,...,Perf\3_DG_N1p4e1_EfficientNetB4_outputbw512hdf...,Seff\3_DeepGalaxy_lustre_1ost_bw512_5350177_hd...,Slurm\3_DG_L1ost_e1_5350177.out,Slurm\3_DG_L1ost_e1_5350177.err,NaN,NaN,PASS,COMPLETE,PASS,[INFO] stderr: 2 warning-like messages detected.
28,DTIO_5352783,6,DeepGalaxy,legacy,dg_train_cli_signature,HIGH,deepgalaxy_cli,5352783,FinisTerrae III,RES-DATA-2022-1-0014,...,Perf\6_DG_N2p8e1_EfficientNetB4_outputbw512hdf...,Seff\6_DeepGalaxy_lustre_1ost_bw512_5352783_hd...,Slurm\6_DG_L1ost_e1_5352783.out,Slurm\6_DG_L1ost_e1_5352783.err,NaN,NaN,PASS,COMPLETE,PASS,[INFO] stderr: 2 warning-like messages detected.
29,DTIO_5353861,26,DeepGalaxy,legacy,dg_train_cli_signature,HIGH,deepgalaxy_cli,5353861,FinisTerrae III,RES-DATA-2022-1-0014,...,Perf\26_DG_N2p8e1_EfficientNetB4_outputbw512hd...,Seff\26_DeepGalaxy_lustre_1ost_bw512_5353861_h...,Slurm\26_DG_L1ost_e1_5353861.out,Slurm\26_DG_L1ost_e1_5353861.err,NaN,NaN,PASS,COMPLETE,PASS,[INFO] stderr: 2 warning-like messages detected.
30,DTIO_5366451,38,DeepGalaxy,legacy,dg_train_cli_signature,HIGH,deepgalaxy_cli,5366451,FinisTerrae III,RES-DATA-2022-1-0014,...,Perf\38_DG_N16p64e1_EfficientNetB4_outputbw512...,Seff\38_DeepGalaxy_lustre_1ost_bw512_5366451_h...,Slurm\38_DG_L1ost_e1_5366451.out,Slurm\38_DG_L1ost_e1_5366451.err,NaN,NaN,PASS,COMPLETE,PASS,[INFO] stderr: 2 warning-like messages detected.
31,DTIO_5369484,39,DeepGalaxy,legacy,dg_train_cli_signature,HIGH,deepgalaxy_cli,5369484,FinisTerrae III,RES-DATA-2022-1-0014,...,Perf\39_DG_N16p64e1_EfficientNetB4_outputbw512...,Seff\39_DeepGalaxy_lustre_1ost_bw512_5369484_h...,Slurm\39_DG_L1ost_e1_5369484.out,Slurm\39_DG_L1ost_e1_5369484.err,NaN,NaN,PASS,COMPLETE,PASS,[INFO] stderr: 2 warning-like messages detected.
32,DTIO_8773752,29,DeepGalaxy,legacy,dg_train_cli_signature,HIGH,deepgalaxy_cli,8773752,FinisTerrae III,RES-DATA-2022-1-0014,...,Perf\29_DG_N4p16e1_EfficientNetB4_outputbw512h...,Seff\29_DeepGalaxy_lustre_1ost_bw512_8773752_h...,Slurm\29_DG_L1ost_e1_8773752.out,Slurm\29_DG_L1ost_e1_8773752.err,NaN,NaN,PASS,COMPLETE,PASS,[INFO] stderr: 2 warning-like messages detected.
33,DTIO_8784568,9,DeepGalaxy,legacy,dg_train_cli_signature,HIGH,deepgalaxy_cli,8784568,FinisTerrae III,RES-DATA-2022-1-0014,...,Perf\9_DG_N4p16e1_EfficientNetB4_outputbw512hd...,Seff\9_DG_L1ost_bw512_8784568_hdf5_seff_JSC24.txt,Slurm\9_DG_L1ost_e1_8784568.out,Slurm\9_DG_L1ost_e1_8784568.err,NaN,NaN,PASS,COMPLETE,PASS,[INFO] stderr: 2 warning-like messages detected.
34,DTIO_8787065,19,DeepGalaxy,legacy,dg_train_cli_signature,HIGH,deepgalaxy_cli,8787065,FinisTerrae III,RES-DATA-2022-1-0014,...,Perf\19_DG_N16p64e1_EfficientNetB4_outputbw512...,Seff\19_DG_L1ost_bw512_8787065_hdf5_seff_JSC24...,Slurm\19_DG_L1ost_e1_8787065.out,Slurm\19_DG_L1ost_e1_8787065.err,NaN,NaN,PASS,COMPLETE,PASS,[INFO] stderr: 2 warning-like messages detected.
35,DTIO_8806303,20,DeepGalaxy,legacy,dg_train_cli_signature,HIGH,deepgalaxy_cli,8806303,FinisTerrae III,RES-DATA-2022-1-0014,...,Perf\20_DG_N16p64e1_EfficientNetB4_outputbw512...,Seff\20_DG_L1ost_bw512_8806303_hdf5_seff_JSC24...,Slurm\20_DG_L1ost_1e_8806303.out,Slurm\20_DG_L1ost_1e_8806303.err,NaN,NaN,PASS,COMPLETE,PASS,[INFO] stderr: 2 warning-like messages detected.
36,DTIO_8810008,10,DeepGalaxy,legacy,dg_train_cli_signature,HIGH,deepgalaxy_cli,8810008,FinisTerrae III,RES-DATA-2022-1-0014,...,Perf\10_DG_N4p16e1_EfficientNetB4_outputbw512h...,Seff\10_DeepGalaxy_lustre_1ost_bw512_8810008_h...,Slurm\10_DG_L1ost_1e_8810008.out,Slurm\10_DG_L1ost_1e_8810008.err,NaN,NaN,PASS,COMPLETE,PASS,[INFO] stderr: 2 warning-like messages detected.
37,DTIO_8849686,17,DeepGalaxy,legacy,dg_train_cli_signature,HIGH,deepgalaxy_cli,8849686,FinisTerrae III,RES-DATA-2022-1-0014,...,Perf\17_DG_N12p48e1_EfficientNetB4_outputbw512...,Seff\17_DG_L1ost_bw512_8849686_hdf5_seff_JSC24...,Slurm\17_DG_L1ost_1e_8849686.out,Slurm\17_DG_L1ost_1e_8849686.err,NaN,NaN,PASS,COMPLETE,PASS,[INFO] stderr: 2 warning-like messages detected.
38,DTIO_8850850,14,DeepGalaxy,legacy,dg_train_cli_signature,HIGH,deepgalaxy_cli,8850850,FinisTerrae III,RES-DATA-2022-1-0014,...,Perf\14_DG_N8p32e1_EfficientNetB4_outputbw512h...,Seff\14_DG_L1ost_bw512_8850850_hdf5_seff_JSC24...,Slurm\14_DG_L1ost_1e_8850850.out,Slurm\14_DG_L1ost_1e_8850850.err,NaN,NaN,PASS,COMPLETE,PASS,[INFO] stderr: 2 warning-like messages detected.

## 3.1. Métricas científicas de la aplicación

Si el adaptador de la aplicación implementa `parse_application_metrics()` o `parse_application_metric_series()`, DeepTuneIO genera automáticamente `application_metrics_<clasificación>.csv`. El núcleo no presupone nombres concretos como `loss`, `accuracy`, `throughput` o `AUC`; cada adaptador define cómo extraer y normalizar sus resultados.

In [7]:
# El fichero solo existe cuando la aplicación expone métricas científicas.
if 'application_metrics' in outputs:
    application_metrics_df = pd.read_csv(outputs['application_metrics'])
    print('Métricas de aplicación:', outputs['application_metrics'])
    display(application_metrics_df)
else:
    application_metrics_df = pd.DataFrame()
    print('La aplicación/campaña seleccionada no generó métricas científicas adicionales.')

Métricas de aplicación: F:\NoteBooks\Journal_SuperComputing25\Traces\DeepGalaxy\Input\DG_bw512_f3c5x64\lustre_1ost\deeptuneio_index_v10\application_metrics_hdf5.csv

,experiment_id,job_id,application,application_version,step_type,step,metric_name,metric_value,native_metric_name,metric_namespace,source
0,DTIO_4935078,4935078,DeepGalaxy,legacy,epoch,1,loss,6.7458,loss,training,application_stdout
1,DTIO_4935078,4935078,DeepGalaxy,legacy,epoch,1,accuracy,0.0046,sparse_categorical_accuracy,training,application_stdout
2,DTIO_4935078,4935078,DeepGalaxy,legacy,epoch,1,validation_loss,6.2655,val_loss,training,application_stdout
3,DTIO_4935078,4935078,DeepGalaxy,legacy,epoch,1,validation_accuracy,0.0128,val_sparse_categorical_accuracy,training,application_stdout
4,DTIO_4935078,4935078,DeepGalaxy,legacy,epoch,1,training_time_s,25120.0000,keras_epoch_elapsed_seconds,training,application_stdout
...,...,...,...,...,...,...,...,...,...,...,...
267,DTIO_8850850,8850850,DeepGalaxy,legacy,epoch,1,validation_loss,11.3533,val_loss,training,application_stdout
268,DTIO_8850850,8850850,DeepGalaxy,legacy,epoch,1,validation_accuracy,0.0022,val_sparse_categorical_accuracy,training,application_stdout
269,DTIO_8850850,8850850,DeepGalaxy,legacy,epoch,1,training_time_s,4006.0000,keras_epoch_elapsed_seconds,training,application_stdout
270,DTIO_8850850,8850850,DeepGalaxy,legacy,epoch,1,step_time_s,17.0000,keras_seconds_per_step,training,application_stdout
271,DTIO_8850850,8850850,DeepGalaxy,legacy,epoch,1,steps,224.0000,keras_steps,training,application_stdout

### Resumen de métricas por ejecución

Para aplicaciones de entrenamiento, como DeepGalaxy, esta vista permite comprobar los resultados finales por `JobID` sin incorporarlos a las firmas de configuración. Las métricas siguen siendo **resultados del experimento**, no parámetros de configuración.

In [8]:
if not application_metrics_df.empty:
    metrics_summary_df = (
        application_metrics_df
        .pivot_table(
            index=['experiment_id','job_id','application','application_version','step_type','step'],
            columns='metric_name',
            values='metric_value',
            aggfunc='first'
        )
        .reset_index()
    )
    display(metrics_summary_df)
else:
    print('No hay métricas de aplicación para resumir.')

metric_name,experiment_id,job_id,application,application_version,step_type,step,accuracy,loss,step_time_s,steps,training_time_s,validation_accuracy,validation_loss
0,DTIO_4935078,4935078,DeepGalaxy,legacy,epoch,1,0.0046,6.7458,14.0,1789.0,25120.0,0.012800,6.2655
1,DTIO_4969259,4969259,DeepGalaxy,legacy,epoch,1,0.0044,6.7387,14.0,1789.0,24887.0,0.010100,6.4730
2,DTIO_4998171,4998171,DeepGalaxy,legacy,epoch,1,0.0077,6.5260,14.0,895.0,12814.0,0.003200,11.7848
3,DTIO_5004132,5004132,DeepGalaxy,legacy,epoch,1,0.0042,6.6145,16.0,447.0,7175.0,0.003100,17.5969
4,DTIO_5005753,5005753,DeepGalaxy,legacy,epoch,1,0.0033,6.8034,27.0,224.0,6345.0,0.003100,7.1425
5,DTIO_5006747,5006747,DeepGalaxy,legacy,epoch,1,0.0036,6.8478,19.0,149.0,2934.0,0.002800,15.9294
6,DTIO_5136097,5136097,DeepGalaxy,legacy,epoch,1,0.0065,6.5814,18.0,895.0,16487.0,0.024400,5.8538
7,DTIO_5145754,5145754,DeepGalaxy,legacy,epoch,1,0.0056,6.5992,16.0,895.0,14541.0,0.013100,6.3585
8,DTIO_5147852,5147852,DeepGalaxy,legacy,epoch,1,0.0075,6.5608,16.0,895.0,14175.0,0.020400,7.3447
9,DTIO_5164453,5164453,DeepGalaxy,legacy,epoch,1,0.0054,6.6159,16.0,895.0,14730.0,NaN,6.5118
10,DTIO_5171929,5171929,DeepGalaxy,legacy,epoch,1,0.0022,7.0635,26.0,149.0,4087.0,0.000559,10025.0254
11,DTIO_5172393,5172393,DeepGalaxy,legacy,epoch,1,0.0058,6.6909,19.0,149.0,2878.0,0.001800,14.5448
12,DTIO_5173520,5173520,DeepGalaxy,legacy,epoch,1,0.0017,7.1043,19.0,149.0,2915.0,0.000979,7.1199
13,DTIO_5178759,5178759,DeepGalaxy,legacy,epoch,1,0.0043,6.5691,15.0,224.0,3526.0,0.003500,7.2453
14,DTIO_5181608,5181608,DeepGalaxy,legacy,epoch,1,0.0037,6.6729,21.0,224.0,4746.0,0.001500,17.3245
15,DTIO_5182586,5182586,DeepGalaxy,legacy,epoch,1,0.0032,6.7508,16.0,224.0,3565.0,0.001300,12.3323
16,DTIO_5183430,5183430,DeepGalaxy,legacy,epoch,1,0.0039,6.6249,16.0,224.0,3670.0,0.000558,16.0308
17,DTIO_5184753,5184753,DeepGalaxy,legacy,epoch,1,0.0067,6.4446,17.0,447.0,7709.0,0.004200,8.8306
18,DTIO_5185397,5185397,DeepGalaxy,legacy,epoch,1,0.0050,6.5509,15.0,447.0,6738.0,0.009100,6.2042
19,DTIO_5186976,5186976,DeepGalaxy,legacy,epoch,1,0.0050,6.7282,15.0,1789.0,27727.0,0.012200,6.4687
20,DTIO_5189973,5189973,DeepGalaxy,legacy,epoch,1,0.0049,6.5627,16.0,447.0,7510.0,0.017300,6.1597
21,DTIO_5196039,5196039,DeepGalaxy,legacy,epoch,1,0.0046,6.7521,15.0,1789.0,26661.0,0.002200,7.2139
22,DTIO_5317272,5317272,DeepGalaxy,legacy,epoch,1,0.0027,6.8270,16.0,1789.0,28894.0,0.001800,7.1234
23,DTIO_5333215,5333215,DeepGalaxy,legacy,epoch,1,0.0027,6.9549,20.0,112.0,2334.0,0.002200,52.4250
24,DTIO_5347797,5347797,DeepGalaxy,legacy,epoch,1,0.0017,7.0806,20.0,149.0,3163.0,0.000280,7.8959
25,DTIO_5348184,5348184,DeepGalaxy,legacy,epoch,1,0.0015,6.9211,22.0,224.0,4935.0,0.001300,7.1186
26,DTIO_5349515,5349515,DeepGalaxy,legacy,epoch,1,0.0016,6.8255,23.0,224.0,5394.0,0.001500,7.6383
27,DTIO_5350177,5350177,DeepGalaxy,legacy,epoch,1,0.0029,6.8329,16.0,1789.0,27862.0,0.000559,7.2081
28,DTIO_5352783,5352783,DeepGalaxy,legacy,epoch,1,0.0078,6.5511,18.0,895.0,15927.0,0.017900,6.5759
29,DTIO_5353861,5353861,DeepGalaxy,legacy,epoch,1,0.0107,6.4694,17.0,895.0,15342.0,0.022300,6.6205
30,DTIO_5366451,5366451,DeepGalaxy,legacy,epoch,1,0.0021,7.3471,20.0,112.0,2334.0,0.000698,829.5873
31,DTIO_5369484,5369484,DeepGalaxy,legacy,epoch,1,0.0033,7.1571,21.0,112.0,2513.0,0.001100,71.0345
32,DTIO_8773752,8773752,DeepGalaxy,legacy,epoch,1,0.0020,6.7338,15.0,447.0,6924.0,0.003300,6.5834
33,DTIO_8784568,8784568,DeepGalaxy,legacy,epoch,1,0.0046,6.6367,14.0,447.0,6422.0,0.000000,16.4289
34,DTIO_8787065,8787065,DeepGalaxy,legacy,epoch,1,0.0028,7.0617,25.0,112.0,2993.0,0.000837,60.8505
35,DTIO_8806303,8806303,DeepGalaxy,legacy,epoch,1,0.0027,7.0927,25.0,112.0,2911.0,0.000698,267.5431
36,DTIO_8810008,8810008,DeepGalaxy,legacy,epoch,1,0.0070,6.4605,16.0,447.0,7146.0,0.010600,6.8973
37,DTIO_8849686,8849686,DeepGalaxy,legacy,epoch,1,0.0025,6.9609,17.0,149.0,2696.0,0.000839,10.6520
38,DTIO_8850850,8850850,DeepGalaxy,legacy,epoch,1,0.0033,6.6246,17.0,224.0,4006.0,0.002200,11.3533

### Ejemplo: métricas de entrenamiento normalizadas

Cuando el adaptador proporciona nombres normalizados, pueden visualizarse de forma uniforme. Esta celda no es obligatoria y funciona solo si esas métricas existen.

In [9]:
if not application_metrics_df.empty:
    wanted = {
        'loss', 'accuracy', 'validation_loss', 'validation_accuracy',
        'training_time_s', 'step_time_s', 'steps'
    }
    available = sorted(set(application_metrics_df['metric_name']) & wanted)
    if available:
        display(
            application_metrics_df[
                application_metrics_df['metric_name'].isin(available)
            ][[
                'experiment_id','job_id','step_type','step',
                'metric_name','metric_value','native_metric_name','source'
            ]]
        )
    else:
        print('La aplicación seleccionada no expone estas métricas normalizadas.')

,experiment_id,job_id,step_type,step,metric_name,metric_value,native_metric_name,source
0,DTIO_4935078,4935078,epoch,1,loss,6.7458,loss,application_stdout
1,DTIO_4935078,4935078,epoch,1,accuracy,0.0046,sparse_categorical_accuracy,application_stdout
2,DTIO_4935078,4935078,epoch,1,validation_loss,6.2655,val_loss,application_stdout
3,DTIO_4935078,4935078,epoch,1,validation_accuracy,0.0128,val_sparse_categorical_accuracy,application_stdout
4,DTIO_4935078,4935078,epoch,1,training_time_s,25120.0000,keras_epoch_elapsed_seconds,application_stdout
...,...,...,...,...,...,...,...,...
267,DTIO_8850850,8850850,epoch,1,validation_loss,11.3533,val_loss,application_stdout
268,DTIO_8850850,8850850,epoch,1,validation_accuracy,0.0022,val_sparse_categorical_accuracy,application_stdout
269,DTIO_8850850,8850850,epoch,1,training_time_s,4006.0000,keras_epoch_elapsed_seconds,application_stdout
270,DTIO_8850850,8850850,epoch,1,step_time_s,17.0000,keras_seconds_per_step,application_stdout
271,DTIO_8850850,8850850,epoch,1,steps,224.0000,keras_steps,application_stdout

## 4. Estados de ejecución e instrumentación

In [10]:
cols = [
    'experiment_id','job_id','application','application_version',
    'application_version_source','application_version_confidence',
    'job_state','exit_code',
    'execution_status','instrumentation_status','metadata_status',
    'stdout_available','stderr_available','darshan_available'
]
df[cols]

,experiment_id,job_id,application,application_version,application_version_source,application_version_confidence,job_state,exit_code,execution_status,instrumentation_status,metadata_status,stdout_available,stderr_available,darshan_available
0,DTIO_4935078,4935078,DeepGalaxy,legacy,dg_train_cli_signature,HIGH,COMPLETED,0,PASS,COMPLETE,PASS,True,True,True
1,DTIO_4969259,4969259,DeepGalaxy,legacy,dg_train_cli_signature,HIGH,COMPLETED,0,PASS,COMPLETE,PASS,True,True,True
2,DTIO_4998171,4998171,DeepGalaxy,legacy,dg_train_cli_signature,HIGH,COMPLETED,0,PASS,COMPLETE,PASS,True,True,True
3,DTIO_5004132,5004132,DeepGalaxy,legacy,dg_train_cli_signature,HIGH,COMPLETED,0,PASS,COMPLETE,PASS,True,True,True
4,DTIO_5005753,5005753,DeepGalaxy,legacy,dg_train_cli_signature,HIGH,COMPLETED,0,PASS,COMPLETE,PASS,True,True,True
5,DTIO_5006747,5006747,DeepGalaxy,legacy,dg_train_cli_signature,HIGH,COMPLETED,0,PASS,COMPLETE,PASS,True,True,True
6,DTIO_5136097,5136097,DeepGalaxy,legacy,dg_train_cli_signature,HIGH,COMPLETED,0,PASS,COMPLETE,PASS,True,True,True
7,DTIO_5145754,5145754,DeepGalaxy,legacy,dg_train_cli_signature,HIGH,COMPLETED,0,PASS,COMPLETE,PASS,True,True,True
8,DTIO_5147852,5147852,DeepGalaxy,legacy,dg_train_cli_signature,HIGH,COMPLETED,0,PASS,COMPLETE,PASS,True,True,True
9,DTIO_5164453,5164453,DeepGalaxy,legacy,dg_train_cli_signature,HIGH,COMPLETED,0,PASS,COMPLETE,PASS,True,True,True
10,DTIO_5171929,5171929,DeepGalaxy,legacy,dg_train_cli_signature,HIGH,COMPLETED,0,PASS,COMPLETE,PASS,True,True,True
11,DTIO_5172393,5172393,DeepGalaxy,legacy,dg_train_cli_signature,HIGH,COMPLETED,0,PASS,COMPLETE,PASS,True,True,True
12,DTIO_5173520,5173520,DeepGalaxy,legacy,dg_train_cli_signature,HIGH,COMPLETED,0,PASS,COMPLETE,PASS,True,True,True
13,DTIO_5178759,5178759,DeepGalaxy,legacy,dg_train_cli_signature,HIGH,COMPLETED,0,PASS,COMPLETE,PASS,True,True,True
14,DTIO_5181608,5181608,DeepGalaxy,legacy,dg_train_cli_signature,HIGH,COMPLETED,0,PASS,COMPLETE,PASS,True,True,True
15,DTIO_5182586,5182586,DeepGalaxy,legacy,dg_train_cli_signature,HIGH,COMPLETED,0,PASS,COMPLETE,PASS,True,True,True
16,DTIO_5183430,5183430,DeepGalaxy,legacy,dg_train_cli_signature,HIGH,COMPLETED,0,PASS,COMPLETE,PASS,True,True,True
17,DTIO_5184753,5184753,DeepGalaxy,legacy,dg_train_cli_signature,HIGH,COMPLETED,0,PASS,COMPLETE,PASS,True,True,True
18,DTIO_5185397,5185397,DeepGalaxy,legacy,dg_train_cli_signature,HIGH,COMPLETED,0,PASS,COMPLETE,PASS,True,True,True
19,DTIO_5186976,5186976,DeepGalaxy,legacy,dg_train_cli_signature,HIGH,COMPLETED,0,PASS,COMPLETE,PASS,True,True,True
20,DTIO_5189973,5189973,DeepGalaxy,legacy,dg_train_cli_signature,HIGH,COMPLETED,0,PASS,COMPLETE,PASS,True,True,True
21,DTIO_5196039,5196039,DeepGalaxy,legacy,dg_train_cli_signature,HIGH,COMPLETED,0,PASS,COMPLETE,PASS,True,True,True
22,DTIO_5317272,5317272,DeepGalaxy,legacy,dg_train_cli_signature,HIGH,COMPLETED,0,PASS,COMPLETE,PASS,True,True,True
23,DTIO_5333215,5333215,DeepGalaxy,legacy,dg_train_cli_signature,HIGH,COMPLETED,0,PASS,COMPLETE,PASS,True,True,True
24,DTIO_5347797,5347797,DeepGalaxy,legacy,dg_train_cli_signature,HIGH,COMPLETED,0,PASS,COMPLETE,PASS,True,True,True
25,DTIO_5348184,5348184,DeepGalaxy,legacy,dg_train_cli_signature,HIGH,COMPLETED,0,PASS,COMPLETE,PASS,True,True,True
26,DTIO_5349515,5349515,DeepGalaxy,legacy,dg_train_cli_signature,HIGH,COMPLETED,0,PASS,COMPLETE,PASS,True,True,True
27,DTIO_5350177,5350177,DeepGalaxy,legacy,dg_train_cli_signature,HIGH,COMPLETED,0,PASS,COMPLETE,PASS,True,True,True
28,DTIO_5352783,5352783,DeepGalaxy,legacy,dg_train_cli_signature,HIGH,COMPLETED,0,PASS,COMPLETE,PASS,True,True,True
29,DTIO_5353861,5353861,DeepGalaxy,legacy,dg_train_cli_signature,HIGH,COMPLETED,0,PASS,COMPLETE,PASS,True,True,True
30,DTIO_5366451,5366451,DeepGalaxy,legacy,dg_train_cli_signature,HIGH,COMPLETED,0,PASS,COMPLETE,PASS,True,True,True
31,DTIO_5369484,5369484,DeepGalaxy,legacy,dg_train_cli_signature,HIGH,COMPLETED,0,PASS,COMPLETE,PASS,True,True,True
32,DTIO_8773752,8773752,DeepGalaxy,legacy,dg_train_cli_signature,HIGH,COMPLETED,0,PASS,COMPLETE,PASS,True,True,True
33,DTIO_8784568,8784568,DeepGalaxy,legacy,dg_train_cli_signature,HIGH,COMPLETED,0,PASS,COMPLETE,PASS,True,True,True
34,DTIO_8787065,8787065,DeepGalaxy,legacy,dg_train_cli_signature,HIGH,COMPLETED,0,PASS,COMPLETE,PASS,True,True,True
35,DTIO_8806303,8806303,DeepGalaxy,legacy,dg_train_cli_signature,HIGH,COMPLETED,0,PASS,COMPLETE,PASS,True,True,True
36,DTIO_8810008,8810008,DeepGalaxy,legacy,dg_train_cli_signature,HIGH,COMPLETED,0,PASS,COMPLETE,PASS,True,True,True
37,DTIO_8849686,8849686,DeepGalaxy,legacy,dg_train_cli_signature,HIGH,COMPLETED,0,PASS,COMPLETE,PASS,True,True,True
38,DTIO_8850850,8850850,DeepGalaxy,legacy,dg_train_cli_signature,HIGH,COMPLETED,0,PASS,COMPLETE,PASS,True,True,True

## 5. Ver ejecuciones sin Darshan

In [11]:
df[df['instrumentation_status'] == 'MISSING'][[
    'experiment_id','job_id','application','execution_status',
    'stdout_file','stderr_file'
]]

Empty DataFrame
Columns: [experiment_id, job_id, application, execution_status, stdout_file, stderr_file]
Index: []

## 6. Ver warnings / errores detectados

In [12]:
df[(df['warning_count'] > 0) | (df['error_count'] > 0)][[
    'experiment_id','job_id','warning_count','error_count',
    'execution_status','stderr_file'
]]

,experiment_id,job_id,warning_count,error_count,execution_status,stderr_file
0,DTIO_4935078,4935078,2,0,PASS,Slurm\1_DG_L1ost_e1_4935078.err
1,DTIO_4969259,4969259,2,0,PASS,Slurm\21_DG_L1ost_e1_4969259.err
2,DTIO_4998171,4998171,2,0,PASS,Slurm\7_DG_L1ost_e1_4998171.err
3,DTIO_5004132,5004132,2,0,PASS,Slurm\27_DG_L1ost_e1_5004132.err
4,DTIO_5005753,5005753,2,0,PASS,Slurm\31_DG_L1ost_e1_5005753.err
5,DTIO_5006747,5006747,2,0,PASS,Slurm\35_DG_L1ost_e1_5006747.err
6,DTIO_5136097,5136097,2,0,PASS,Slurm\24_DG_L1ost_e1_5136097.err
7,DTIO_5145754,5145754,2,0,PASS,Slurm\25_DG_L1ost_e1_5145754.err
8,DTIO_5147852,5147852,2,0,PASS,Slurm\4_DG_L1ost_e1_5147852.err
9,DTIO_5164453,5164453,2,0,PASS,Slurm\5_DG_L1ost_e1_5164453.err
10,DTIO_5171929,5171929,2,0,PASS,Slurm\15_DG_L1ost_e1_5171929.err
11,DTIO_5172393,5172393,2,0,PASS,Slurm\16_DG_L1ost_e1_5172393.err
12,DTIO_5173520,5173520,2,0,PASS,Slurm\36_DG_L1ost_e1_5173520.err
13,DTIO_5178759,5178759,2,0,PASS,Slurm\11_DG_L1ost_e1_5178759.err
14,DTIO_5181608,5181608,2,0,PASS,Slurm\12_DG_L1ost_e1_5181608.err
15,DTIO_5182586,5182586,2,0,PASS,Slurm\32_DG_L1ost_e1_5182586.err
16,DTIO_5183430,5183430,2,0,PASS,Slurm\33_DG_L1ost_e1_5183430.err
17,DTIO_5184753,5184753,2,0,PASS,Slurm\8_DG_L1ost_e1_5184753.err
18,DTIO_5185397,5185397,2,0,PASS,Slurm\28_DG_L1ost_e1_5185397.err
19,DTIO_5186976,5186976,2,0,PASS,Slurm\22_DG_L1ost_e1_5186976.err
20,DTIO_5189973,5189973,2,0,PASS,Slurm\30_DG_L1ost_e1_5189973.err
21,DTIO_5196039,5196039,2,0,PASS,Slurm\2_DG_L1ost_e1_5196039.err
22,DTIO_5317272,5317272,2,0,PASS,Slurm\23_DG_L1ost_e1_5317272.err
23,DTIO_5333215,5333215,2,0,PASS,Slurm\18_DG_L1ost_e1_5333215.err
24,DTIO_5347797,5347797,2,0,PASS,Slurm\37_DG_L1ost_e1_5347797.err
25,DTIO_5348184,5348184,2,0,PASS,Slurm\34_DG_L1ost_e1_5348184.err
26,DTIO_5349515,5349515,2,0,PASS,Slurm\13_DG_L1ost_e1_5349515.err
27,DTIO_5350177,5350177,2,0,PASS,Slurm\3_DG_L1ost_e1_5350177.err
28,DTIO_5352783,5352783,2,0,PASS,Slurm\6_DG_L1ost_e1_5352783.err
29,DTIO_5353861,5353861,2,0,PASS,Slurm\26_DG_L1ost_e1_5353861.err
30,DTIO_5366451,5366451,2,0,PASS,Slurm\38_DG_L1ost_e1_5366451.err
31,DTIO_5369484,5369484,2,0,PASS,Slurm\39_DG_L1ost_e1_5369484.err
32,DTIO_8773752,8773752,2,0,PASS,Slurm\29_DG_L1ost_e1_8773752.err
33,DTIO_8784568,8784568,2,0,PASS,Slurm\9_DG_L1ost_e1_8784568.err
34,DTIO_8787065,8787065,2,0,PASS,Slurm\19_DG_L1ost_e1_8787065.err
35,DTIO_8806303,8806303,2,0,PASS,Slurm\20_DG_L1ost_1e_8806303.err
36,DTIO_8810008,8810008,2,0,PASS,Slurm\10_DG_L1ost_1e_8810008.err
37,DTIO_8849686,8849686,2,0,PASS,Slurm\17_DG_L1ost_1e_8849686.err
38,DTIO_8850850,8850850,2,0,PASS,Slurm\14_DG_L1ost_1e_8850850.err

## 7. Trazabilidad con el artículo

Los campos `paper_figures` y `paper_tables` se completan explícitamente después de validar qué ejecuciones sustentan cada resultado.

## 8. Resumen semántico de diagnósticos

Las ocurrencias repetidas por proceso se conservan, pero también se agrupan por tipo diagnóstico.

In [13]:
df[[
    'experiment_id','job_id','execution_status',
    'warning_count','error_count','diagnostic_occurrences',
    'diagnostic_types','diagnostic_counts'
]]

,experiment_id,job_id,execution_status,warning_count,error_count,diagnostic_occurrences,diagnostic_types,diagnostic_counts
0,DTIO_4935078,4935078,PASS,2,0,12,"[""generic_warning"", ""tensorrt_unavailable""]","{""cuda_initialization_unavailable"": 0, ""cuda_l..."
1,DTIO_4969259,4969259,PASS,2,0,12,"[""generic_warning"", ""tensorrt_unavailable""]","{""cuda_initialization_unavailable"": 0, ""cuda_l..."
2,DTIO_4998171,4998171,PASS,2,0,24,"[""generic_warning"", ""tensorrt_unavailable""]","{""cuda_initialization_unavailable"": 0, ""cuda_l..."
3,DTIO_5004132,5004132,PASS,2,0,48,"[""generic_warning"", ""tensorrt_unavailable""]","{""cuda_initialization_unavailable"": 0, ""cuda_l..."
4,DTIO_5005753,5005753,PASS,2,0,100,"[""generic_warning"", ""tensorrt_unavailable""]","{""cuda_initialization_unavailable"": 0, ""cuda_l..."
5,DTIO_5006747,5006747,PASS,2,0,145,"[""generic_warning"", ""tensorrt_unavailable""]","{""cuda_initialization_unavailable"": 0, ""cuda_l..."
6,DTIO_5136097,5136097,PASS,2,0,30,"[""generic_warning"", ""tensorrt_unavailable""]","{""cuda_initialization_unavailable"": 0, ""cuda_l..."
7,DTIO_5145754,5145754,PASS,2,0,25,"[""generic_warning"", ""tensorrt_unavailable""]","{""cuda_initialization_unavailable"": 0, ""cuda_l..."
8,DTIO_5147852,5147852,PASS,2,0,24,"[""generic_warning"", ""tensorrt_unavailable""]","{""cuda_initialization_unavailable"": 0, ""cuda_l..."
9,DTIO_5164453,5164453,PASS,2,0,28,"[""generic_warning"", ""tensorrt_unavailable""]","{""cuda_initialization_unavailable"": 0, ""cuda_l..."
10,DTIO_5171929,5171929,PASS,2,0,146,"[""generic_warning"", ""tensorrt_unavailable""]","{""cuda_initialization_unavailable"": 0, ""cuda_l..."
11,DTIO_5172393,5172393,PASS,2,0,144,"[""generic_warning"", ""tensorrt_unavailable""]","{""cuda_initialization_unavailable"": 0, ""cuda_l..."
12,DTIO_5173520,5173520,PASS,2,0,145,"[""generic_warning"", ""tensorrt_unavailable""]","{""cuda_initialization_unavailable"": 0, ""cuda_l..."
13,DTIO_5178759,5178759,PASS,2,0,96,"[""generic_warning"", ""tensorrt_unavailable""]","{""cuda_initialization_unavailable"": 0, ""cuda_l..."
14,DTIO_5181608,5181608,PASS,2,0,96,"[""generic_warning"", ""tensorrt_unavailable""]","{""cuda_initialization_unavailable"": 0, ""cuda_l..."
15,DTIO_5182586,5182586,PASS,2,0,96,"[""generic_warning"", ""tensorrt_unavailable""]","{""cuda_initialization_unavailable"": 0, ""cuda_l..."
16,DTIO_5183430,5183430,PASS,2,0,96,"[""generic_warning"", ""tensorrt_unavailable""]","{""cuda_initialization_unavailable"": 0, ""cuda_l..."
17,DTIO_5184753,5184753,PASS,2,0,48,"[""generic_warning"", ""tensorrt_unavailable""]","{""cuda_initialization_unavailable"": 0, ""cuda_l..."
18,DTIO_5185397,5185397,PASS,2,0,48,"[""generic_warning"", ""tensorrt_unavailable""]","{""cuda_initialization_unavailable"": 0, ""cuda_l..."
19,DTIO_5186976,5186976,PASS,2,0,12,"[""generic_warning"", ""tensorrt_unavailable""]","{""cuda_initialization_unavailable"": 0, ""cuda_l..."
20,DTIO_5189973,5189973,PASS,2,0,48,"[""generic_warning"", ""tensorrt_unavailable""]","{""cuda_initialization_unavailable"": 0, ""cuda_l..."
21,DTIO_5196039,5196039,PASS,2,0,13,"[""generic_warning"", ""tensorrt_unavailable""]","{""cuda_initialization_unavailable"": 0, ""cuda_l..."
22,DTIO_5317272,5317272,PASS,2,0,12,"[""generic_warning"", ""tensorrt_unavailable""]","{""cuda_initialization_unavailable"": 0, ""cuda_l..."
23,DTIO_5333215,5333215,PASS,2,0,192,"[""generic_warning"", ""tensorrt_unavailable""]","{""cuda_initialization_unavailable"": 0, ""cuda_l..."
24,DTIO_5347797,5347797,PASS,2,0,145,"[""generic_warning"", ""tensorrt_unavailable""]","{""cuda_initialization_unavailable"": 0, ""cuda_l..."
25,DTIO_5348184,5348184,PASS,2,0,97,"[""generic_warning"", ""tensorrt_unavailable""]","{""cuda_initialization_unavailable"": 0, ""cuda_l..."
26,DTIO_5349515,5349515,PASS,2,0,96,"[""generic_warning"", ""tensorrt_unavailable""]","{""cuda_initialization_unavailable"": 0, ""cuda_l..."
27,DTIO_5350177,5350177,PASS,2,0,12,"[""generic_warning"", ""tensorrt_unavailable""]","{""cuda_initialization_unavailable"": 0, ""cuda_l..."
28,DTIO_5352783,5352783,PASS,2,0,24,"[""generic_warning"", ""tensorrt_unavailable""]","{""cuda_initialization_unavailable"": 0, ""cuda_l..."
29,DTIO_5353861,5353861,PASS,2,0,25,"[""generic_warning"", ""tensorrt_unavailable""]","{""cuda_initialization_unavailable"": 0, ""cuda_l..."
30,DTIO_5366451,5366451,PASS,2,0,192,"[""generic_warning"", ""tensorrt_unavailable""]","{""cuda_initialization_unavailable"": 0, ""cuda_l..."
31,DTIO_5369484,5369484,PASS,2,0,193,"[""generic_warning"", ""tensorrt_unavailable""]","{""cuda_initialization_unavailable"": 0, ""cuda_l..."
32,DTIO_8773752,8773752,PASS,2,0,48,"[""generic_warning"", ""tensorrt_unavailable""]","{""cuda_initialization_unavailable"": 0, ""cuda_l..."
33,DTIO_8784568,8784568,PASS,2,0,48,"[""generic_warning"", ""tensorrt_unavailable""]","{""cuda_initialization_unavailable"": 0, ""cuda_l..."
34,DTIO_8787065,8787065,PASS,2,0,193,"[""generic_warning"", ""tensorrt_unavailable""]","{""cuda_initialization_unavailable"": 0, ""cuda_l..."
35,DTIO_8806303,8806303,PASS,2,0,194,"[""generic_warning"", ""tensorrt_unavailable""]","{""cuda_initialization_unavailable"": 0, ""cuda_l..."
36,DTIO_8810008,8810008,PASS,2,0,48,"[""generic_warning"", ""tensorrt_unavailable""]","{""cuda_initialization_unavailable"": 0, ""cuda_l..."
37,DTIO_8849686,8849686,PASS,2,0,144,"[""generic_warning"", ""tensorrt_unavailable""]","{""cuda_initialization_unavailable"": 0, ""cuda_l..."
38,DTIO_8850850,8850850,PASS,2,0,96,"[""generic_warning"", ""tensorrt_unavailable""]","{""cuda_initialization_unavailable"": 0, ""cuda_l..."

## 9. Validar el formato de fichero

El campo universal `file_format` se resuelve por prioridad: adaptador/comando de aplicación, DXT, stdout y finalmente nombre de fichero.

In [14]:
df[[
    'experiment_id','job_id','application','application_version',
    'application_version_source','application_version_confidence',
    'file_format','file_format_source','file_format_confidence',
    'instrumentation_status','metadata_status'
]]

,experiment_id,job_id,application,application_version,application_version_source,application_version_confidence,file_format,file_format_source,file_format_confidence,instrumentation_status,metadata_status
0,DTIO_4935078,4935078,DeepGalaxy,legacy,dg_train_cli_signature,HIGH,hdf5,application_command,HIGH,COMPLETE,PASS
1,DTIO_4969259,4969259,DeepGalaxy,legacy,dg_train_cli_signature,HIGH,hdf5,application_command,HIGH,COMPLETE,PASS
2,DTIO_4998171,4998171,DeepGalaxy,legacy,dg_train_cli_signature,HIGH,hdf5,application_command,HIGH,COMPLETE,PASS
3,DTIO_5004132,5004132,DeepGalaxy,legacy,dg_train_cli_signature,HIGH,hdf5,application_command,HIGH,COMPLETE,PASS
4,DTIO_5005753,5005753,DeepGalaxy,legacy,dg_train_cli_signature,HIGH,hdf5,application_command,HIGH,COMPLETE,PASS
5,DTIO_5006747,5006747,DeepGalaxy,legacy,dg_train_cli_signature,HIGH,hdf5,application_command,HIGH,COMPLETE,PASS
6,DTIO_5136097,5136097,DeepGalaxy,legacy,dg_train_cli_signature,HIGH,hdf5,application_command,HIGH,COMPLETE,PASS
7,DTIO_5145754,5145754,DeepGalaxy,legacy,dg_train_cli_signature,HIGH,hdf5,application_command,HIGH,COMPLETE,PASS
8,DTIO_5147852,5147852,DeepGalaxy,legacy,dg_train_cli_signature,HIGH,hdf5,application_command,HIGH,COMPLETE,PASS
9,DTIO_5164453,5164453,DeepGalaxy,legacy,dg_train_cli_signature,HIGH,hdf5,application_command,HIGH,COMPLETE,PASS
10,DTIO_5171929,5171929,DeepGalaxy,legacy,dg_train_cli_signature,HIGH,hdf5,application_command,HIGH,COMPLETE,PASS
11,DTIO_5172393,5172393,DeepGalaxy,legacy,dg_train_cli_signature,HIGH,hdf5,application_command,HIGH,COMPLETE,PASS
12,DTIO_5173520,5173520,DeepGalaxy,legacy,dg_train_cli_signature,HIGH,hdf5,application_command,HIGH,COMPLETE,PASS
13,DTIO_5178759,5178759,DeepGalaxy,legacy,dg_train_cli_signature,HIGH,hdf5,application_command,HIGH,COMPLETE,PASS
14,DTIO_5181608,5181608,DeepGalaxy,legacy,dg_train_cli_signature,HIGH,hdf5,application_command,HIGH,COMPLETE,PASS
15,DTIO_5182586,5182586,DeepGalaxy,legacy,dg_train_cli_signature,HIGH,hdf5,application_command,HIGH,COMPLETE,PASS
16,DTIO_5183430,5183430,DeepGalaxy,legacy,dg_train_cli_signature,HIGH,hdf5,application_command,HIGH,COMPLETE,PASS
17,DTIO_5184753,5184753,DeepGalaxy,legacy,dg_train_cli_signature,HIGH,hdf5,application_command,HIGH,COMPLETE,PASS
18,DTIO_5185397,5185397,DeepGalaxy,legacy,dg_train_cli_signature,HIGH,hdf5,application_command,HIGH,COMPLETE,PASS
19,DTIO_5186976,5186976,DeepGalaxy,legacy,dg_train_cli_signature,HIGH,hdf5,application_command,HIGH,COMPLETE,PASS
20,DTIO_5189973,5189973,DeepGalaxy,legacy,dg_train_cli_signature,HIGH,hdf5,application_command,HIGH,COMPLETE,PASS
21,DTIO_5196039,5196039,DeepGalaxy,legacy,dg_train_cli_signature,HIGH,hdf5,application_command,HIGH,COMPLETE,PASS
22,DTIO_5317272,5317272,DeepGalaxy,legacy,dg_train_cli_signature,HIGH,hdf5,application_command,HIGH,COMPLETE,PASS
23,DTIO_5333215,5333215,DeepGalaxy,legacy,dg_train_cli_signature,HIGH,hdf5,application_command,HIGH,COMPLETE,PASS
24,DTIO_5347797,5347797,DeepGalaxy,legacy,dg_train_cli_signature,HIGH,hdf5,application_command,HIGH,COMPLETE,PASS
25,DTIO_5348184,5348184,DeepGalaxy,legacy,dg_train_cli_signature,HIGH,hdf5,application_command,HIGH,COMPLETE,PASS
26,DTIO_5349515,5349515,DeepGalaxy,legacy,dg_train_cli_signature,HIGH,hdf5,application_command,HIGH,COMPLETE,PASS
27,DTIO_5350177,5350177,DeepGalaxy,legacy,dg_train_cli_signature,HIGH,hdf5,application_command,HIGH,COMPLETE,PASS
28,DTIO_5352783,5352783,DeepGalaxy,legacy,dg_train_cli_signature,HIGH,hdf5,application_command,HIGH,COMPLETE,PASS
29,DTIO_5353861,5353861,DeepGalaxy,legacy,dg_train_cli_signature,HIGH,hdf5,application_command,HIGH,COMPLETE,PASS
30,DTIO_5366451,5366451,DeepGalaxy,legacy,dg_train_cli_signature,HIGH,hdf5,application_command,HIGH,COMPLETE,PASS
31,DTIO_5369484,5369484,DeepGalaxy,legacy,dg_train_cli_signature,HIGH,hdf5,application_command,HIGH,COMPLETE,PASS
32,DTIO_8773752,8773752,DeepGalaxy,legacy,dg_train_cli_signature,HIGH,hdf5,application_command,HIGH,COMPLETE,PASS
33,DTIO_8784568,8784568,DeepGalaxy,legacy,dg_train_cli_signature,HIGH,hdf5,application_command,HIGH,COMPLETE,PASS
34,DTIO_8787065,8787065,DeepGalaxy,legacy,dg_train_cli_signature,HIGH,hdf5,application_command,HIGH,COMPLETE,PASS
35,DTIO_8806303,8806303,DeepGalaxy,legacy,dg_train_cli_signature,HIGH,hdf5,application_command,HIGH,COMPLETE,PASS
36,DTIO_8810008,8810008,DeepGalaxy,legacy,dg_train_cli_signature,HIGH,hdf5,application_command,HIGH,COMPLETE,PASS
37,DTIO_8849686,8849686,DeepGalaxy,legacy,dg_train_cli_signature,HIGH,hdf5,application_command,HIGH,COMPLETE,PASS
38,DTIO_8850850,8850850,DeepGalaxy,legacy,dg_train_cli_signature,HIGH,hdf5,application_command,HIGH,COMPLETE,PASS

### Comprobar formatos detectados

Para DLIO con Darshan, `file_format_source` debería ser `application_command` porque `# exe` contiene `-f`.

In [15]:
df.groupby(['file_format','file_format_source','file_format_confidence'], dropna=False).size().reset_index(name='executions')

  file_format   file_format_source file_format_confidence  executions
0        hdf5  application_command                   HIGH          39

## 10. Configuración experimental normalizada

DeepTuneIO v12 separa parámetros universales, parámetros comunes al formato y parámetros específicos de la aplicación.

In [16]:
normalized_cols = [
    'experiment_id','job_id','application','application_version','file_format',
    'batch_size','number_files','samples_per_file','record_length_bytes','epochs',
    'transfer_size_bytes','transfer_size_label',
    'chunking_enabled','chunk_size_bytes','compression_type','compression_level',
    'nodes','processes','ppn','filesystem','stripe_size_bytes','stripe_count',
    'configuration_source','application_configuration_signature','dataset_configuration_signature','experiment_configuration_signature'
]
df[normalized_cols]

,experiment_id,job_id,application,application_version,file_format,batch_size,number_files,samples_per_file,record_length_bytes,epochs,...,nodes,processes,ppn,filesystem,stripe_size_bytes,stripe_count,configuration_source,application_configuration_signature,dataset_configuration_signature,experiment_configuration_signature
0,DTIO_4935078,4935078,DeepGalaxy,legacy,hdf5,4,NaN,NaN,NaN,1,...,1,4,4,lustre,1048576,1,deepgalaxy_cli,"{""access_strategy"": ""shared"", ""allow_growth"": ...","{""application"": ""DeepGalaxy"", ""application_ver...","{""access_strategy"": ""shared"", ""allow_growth"": ..."
1,DTIO_4969259,4969259,DeepGalaxy,legacy,hdf5,4,NaN,NaN,NaN,1,...,1,4,4,lustre,1048576,1,deepgalaxy_cli,"{""access_strategy"": ""shared_reload_shuffle"", ""...","{""application"": ""DeepGalaxy"", ""application_ver...","{""access_strategy"": ""shared_reload_shuffle"", ""..."
2,DTIO_4998171,4998171,DeepGalaxy,legacy,hdf5,4,NaN,NaN,NaN,1,...,2,8,4,lustre,1048576,1,deepgalaxy_cli,"{""access_strategy"": ""shared"", ""allow_growth"": ...","{""application"": ""DeepGalaxy"", ""application_ver...","{""access_strategy"": ""shared"", ""allow_growth"": ..."
3,DTIO_5004132,5004132,DeepGalaxy,legacy,hdf5,4,NaN,NaN,NaN,1,...,4,16,4,lustre,1048576,1,deepgalaxy_cli,"{""access_strategy"": ""shared_reload_shuffle"", ""...","{""application"": ""DeepGalaxy"", ""application_ver...","{""access_strategy"": ""shared_reload_shuffle"", ""..."
4,DTIO_5005753,5005753,DeepGalaxy,legacy,hdf5,4,NaN,NaN,NaN,1,...,8,32,4,lustre,1048576,1,deepgalaxy_cli,"{""access_strategy"": ""shared_reload_shuffle"", ""...","{""application"": ""DeepGalaxy"", ""application_ver...","{""access_strategy"": ""shared_reload_shuffle"", ""..."
5,DTIO_5006747,5006747,DeepGalaxy,legacy,hdf5,4,NaN,NaN,NaN,1,...,12,48,4,lustre,1048576,1,deepgalaxy_cli,"{""access_strategy"": ""shared_reload_shuffle"", ""...","{""application"": ""DeepGalaxy"", ""application_ver...","{""access_strategy"": ""shared_reload_shuffle"", ""..."
6,DTIO_5136097,5136097,DeepGalaxy,legacy,hdf5,4,NaN,NaN,NaN,1,...,2,8,4,lustre,1048576,1,deepgalaxy_cli,"{""access_strategy"": ""shared_reload_shuffle"", ""...","{""application"": ""DeepGalaxy"", ""application_ver...","{""access_strategy"": ""shared_reload_shuffle"", ""..."
7,DTIO_5145754,5145754,DeepGalaxy,legacy,hdf5,4,NaN,NaN,NaN,1,...,2,8,4,lustre,1048576,1,deepgalaxy_cli,"{""access_strategy"": ""shared_reload_shuffle"", ""...","{""application"": ""DeepGalaxy"", ""application_ver...","{""access_strategy"": ""shared_reload_shuffle"", ""..."
8,DTIO_5147852,5147852,DeepGalaxy,legacy,hdf5,4,NaN,NaN,NaN,1,...,2,8,4,lustre,1048576,1,deepgalaxy_cli,"{""access_strategy"": ""shared"", ""allow_growth"": ...","{""application"": ""DeepGalaxy"", ""application_ver...","{""access_strategy"": ""shared"", ""allow_growth"": ..."
9,DTIO_5164453,5164453,DeepGalaxy,legacy,hdf5,4,NaN,NaN,NaN,1,...,2,8,4,lustre,1048576,1,deepgalaxy_cli,"{""access_strategy"": ""shared"", ""allow_growth"": ...","{""application"": ""DeepGalaxy"", ""application_ver...","{""access_strategy"": ""shared"", ""allow_growth"": ..."
10,DTIO_5171929,5171929,DeepGalaxy,legacy,hdf5,4,NaN,NaN,NaN,1,...,12,48,4,lustre,1048576,1,deepgalaxy_cli,"{""access_strategy"": ""shared"", ""allow_growth"": ...","{""application"": ""DeepGalaxy"", ""application_ver...","{""access_strategy"": ""shared"", ""allow_growth"": ..."
11,DTIO_5172393,5172393,DeepGalaxy,legacy,hdf5,4,NaN,NaN,NaN,1,...,12,48,4,lustre,1048576,1,deepgalaxy_cli,"{""access_strategy"": ""shared"", ""allow_growth"": ...","{""application"": ""DeepGalaxy"", ""application_ver...","{""access_strategy"": ""shared"", ""allow_growth"": ..."
12,DTIO_5173520,5173520,DeepGalaxy,legacy,hdf5,4,NaN,NaN,NaN,1,...,12,48,4,lustre,1048576,1,deepgalaxy_cli,"{""access_strategy"": ""shared_reload_shuffle"", ""...","{""application"": ""DeepGalaxy"", ""application_ver...","{""access_strategy"": ""shared_reload_shuffle"", ""..."
13,DTIO_5178759,5178759,DeepGalaxy,legacy,hdf5,4,NaN,NaN,NaN,1,...,8,32,4,lustre,1048576,1,deepgalaxy_cli,"{""access_strategy"": ""shared"", ""allow_growth"": ...","{""application"": ""DeepGalaxy"", ""application_ver...","{""access_strategy"": ""shared"", ""allow_growth"": ..."
14,DTIO_5181608,5181608,DeepGalaxy,legacy,hdf5,4,NaN,NaN,NaN,1,...,8,32,4,lustre,1048576,1,deepgalaxy_cli,"{""access_strategy"": ""shared"", ""allow_growth"": ...","{""application"": ""DeepGalaxy"", ""application_ver...","{""access_strategy"": ""shared"", ""allow_growth"": ..."
15,DTIO_5182586,5182586,DeepGalaxy,legacy,hdf5,4,NaN,NaN,NaN,1,...,8,32,4,lustre,1048576,1,deepgalaxy_cli,"{""access_strategy"": ""shared_reload_shuffle"", ""...","{""application"": ""DeepGalaxy"", ""application_ver...","{""access_strategy"": ""shared_reload_shuffle"", ""..."
16,DTIO_5183430,5183430,DeepGalaxy,legacy,hdf5,4,NaN,NaN,NaN,1,...,8,32,4,lustre,1048576,1,deepgalaxy_cli,"{""access_strategy"": ""shared_reload_shuffle"", ""...","{""application"": ""DeepGalaxy"", ""application_ver...","{""access_strategy"": ""shared_reload_shuffle"", ""..."
17,DTIO_5184753,5184753,DeepGalaxy,legacy,hdf5,4,NaN,NaN,NaN,1,...,4,16,4,lustre,1048576,1,deepgalaxy_cli,"{""access_strategy"": ""shared"", ""allow_growth"": ...","{""application"": ""DeepGalaxy"", ""application_ver...","{""access_strategy"": ""shared"", ""allow_growth"": ..."
18,DTIO_5185397,5185397,DeepGalaxy,legacy,hdf5,4,NaN,NaN,NaN,1,...,4,16,4,lustre,1048576,1,deepgalaxy_cli,"{""access_strategy"": ""shared_reload_shuffle"", ""...","{""application"": ""DeepGalaxy"", ""application_ver...","{""access_strategy"": ""shared_reload_shuffle"", ""..."
19,DTIO_5186976,5186976,DeepGalaxy,legacy,hdf5,4,NaN,NaN,NaN,1,...,1,4,4,lustre,1048576,1,deepgalaxy_cli,"{""access_strategy"": ""shared_reload_shuffle"", ""...","{""application"": ""DeepGalaxy"", ""application_ver...","{""access_strategy"": ""shared_reload_shuffle"", ""..."
20,DTIO_5189973,5189973,DeepGalaxy,legacy,hdf5,4,NaN,NaN,NaN,1,...,4,16,4,lustre,1048576,1,deepgalaxy_cli,"{""access_strategy"": ""shared_reload_shuffle"", ""...","{""application"": ""DeepGalaxy"", ""application_ver...","{""access_strategy"": ""shared_reload_shuffle"", ""..."
21,DTIO_5196039,5196039,DeepGalaxy,legacy,hdf5,4,NaN,NaN,NaN,1,...,1,4,4,lustre,1048576,1,deepgalaxy_cli,"{""access_strategy"": ""shared"", ""allow_growth"": ...","{""application"": ""DeepGalaxy"", ""application_ver...","{""access_strategy"": ""shared"", ""allow_growth"": ..."
22,DTIO_5317272,5317272,DeepGalaxy,legacy,hdf5,4,NaN,NaN,NaN,1,...,1,4,4,lustre,1048576,1,deepgalaxy_cli,"{""access_strategy"": ""shared_reload_shuffle"", ""...","{""application"": ""DeepGalaxy"", ""application_ver...","{""access_strategy"": ""shared_reload_shuffle"", ""..."
23,DTIO_5333215,5333215,DeepGalaxy,legacy,hdf5,4,NaN,NaN,NaN,1,...,16,64,4,lustre,1048576,1,deepgalaxy_cli,"{""access_strategy"": ""shared"", ""allow_growth"": ...","{""application"": ""DeepGalaxy"", ""application_ver...","{""access_strategy"": ""shared"", ""allow_growth"": ..."
24,DTIO_5347797,5347797,DeepGalaxy,legacy,hdf5,4,NaN,NaN,NaN,1,...,12,48,4,lustre,1048576,1,deepgalaxy_cli,"{""access_strategy"": ""shared_reload_shuffle"", ""...","{""application"": ""DeepGalaxy"", ""application_ver...","{""access_strategy"": ""shared_reload_shuffle"", ""..."
25,DTIO_5348184,5348184,DeepGalaxy,legacy,hdf5,4,NaN,NaN,NaN,1,...,8,32,4,lustre,1048576,1,deepgalaxy_cli,"{""access_strategy"": ""shared_reload_shuffle"", ""...","{""application"": ""DeepGalaxy"", ""application_ver...","{""access_strategy"": ""shared_reload_shuffle"", ""..."
26,DTIO_5349515,5349515,DeepGalaxy,legacy,hdf5,4,NaN,NaN,NaN,1,...,8,32,4,lustre,1048576,1,deepgalaxy_cli,"{""access_strategy"": ""shared"", ""allow_growth"": ...","{""application"": ""DeepGalaxy"", ""application_ver...","{""access_strategy"": ""shared"", ""allow_growth"": ..."
27,DTIO_5350177,5350177,DeepGalaxy,legacy,hdf5,4,NaN,NaN,NaN,1,...,1,4,4,lustre,1048576,1,deepgalaxy_cli,"{""access_strategy"": ""shared"", ""allow_growth"": ...","{""application"": ""DeepGalaxy"", ""application_ver...","{""access_strategy"": ""shared"", ""allow_growth"": ..."
28,DTIO_5352783,5352783,DeepGalaxy,legacy,hdf5,4,NaN,NaN,NaN,1,...,2,8,4,lustre,1048576,1,deepgalaxy_cli,"{""access_strategy"": ""shared"", ""allow_growth"": ...","{""application"": ""DeepGalaxy"", ""application_ver...","{""access_strategy"": ""shared"", ""allow_growth"": ..."
29,DTIO_5353861,5353861,DeepGalaxy,legacy,hdf5,4,NaN,NaN,NaN,1,...,2,8,4,lustre,1048576,1,deepgalaxy_cli,"{""access_strategy"": ""shared_reload_shuffle"", ""...","{""application"": ""DeepGalaxy"", ""application_ver...","{""access_strategy"": ""shared_reload_shuffle"", ""..."
30,DTIO_5366451,5366451,DeepGalaxy,legacy,hdf5,4,NaN,NaN,NaN,1,...,16,64,4,lustre,1048576,1,deepgalaxy_cli,"{""access_strategy"": ""shared_reload_shuffle"", ""...","{""application"": ""DeepGalaxy"", ""application_ver...","{""access_strategy"": ""shared_reload_shuffle"", ""..."
31,DTIO_5369484,5369484,DeepGalaxy,legacy,hdf5,4,NaN,NaN,NaN,1,...,16,64,4,lustre,1048576,1,deepgalaxy_cli,"{""access_strategy"": ""shared_reload_shuffle"", ""...","{""application"": ""DeepGalaxy"", ""application_ver...","{""access_strategy"": ""shared_reload_shuffle"", ""..."
32,DTIO_8773752,8773752,DeepGalaxy,legacy,hdf5,4,NaN,NaN,NaN,1,...,4,16,4,lustre,1048576,1,deepgalaxy_cli,"{""access_strategy"": ""shared_reload_shuffle"", ""...","{""application"": ""DeepGalaxy"", ""application_ver...","{""access_strategy"": ""shared_reload_shuffle"", ""..."
33,DTIO_8784568,8784568,DeepGalaxy,legacy,hdf5,4,NaN,NaN,NaN,1,...,4,16,4,lustre,1048576,1,deepgalaxy_cli,"{""access_strategy"": ""shared"", ""allow_growth"": ...","{""application"": ""DeepGalaxy"", ""application_ver...","{""access_strategy"": ""shared"", ""allow_growth"": ..."
34,DTIO_8787065,8787065,DeepGalaxy,legacy,hdf5,4,NaN,NaN,NaN,1,...,16,64,4,lustre,1048576,1,deepgalaxy_cli,"{""access_strategy"": ""shared"", ""allow_growth"": ...","{""application"": ""DeepGalaxy"", ""application_ver...","{""access_strategy"": ""shared"", ""allow_growth"": ..."
35,DTIO_8806303,8806303,DeepGalaxy,legacy,hdf5,4,NaN,NaN,NaN,1,...,16,64,4,lustre,1048576,1,deepgalaxy_cli,"{""access_strategy"": ""shared"", ""allow_growth"": ...","{""application"": ""DeepGalaxy"", ""application_ver...","{""access_strategy"": ""shared"", ""allow_growth"": ..."
36,DTIO_8810008,8810008,DeepGalaxy,legacy,hdf5,4,NaN,NaN,NaN,1,...,4,16,4,lustre,1048576,1,deepgalaxy_cli,"{""access_strategy"": ""shared"", ""allow_growth"": ...","{""application"": ""DeepGalaxy"", ""application_ver...","{""access_strategy"": ""shared"", ""allow_growth"": ..."
37,DTIO_8849686,8849686,DeepGalaxy,legacy,hdf5,4,NaN,NaN,NaN,1,...,12,48,4,lustre,1048576,1,deepgalaxy_cli,"{""access_strategy"": ""shared"", ""allow_growth"": ...","{""application"": ""DeepGalaxy"", ""application_ver...","{""access_strategy"": ""shared"", ""allow_growth"": ..."
38,DTIO_8850850,8850850,DeepGalaxy,legacy,hdf5,4,NaN,NaN,NaN,1,...,8,32,4,lustre,1048576,1,deepgalaxy_cli,"{""access_strategy"": ""shared"", ""allow_growth"": ...","{""application"": ""DeepGalaxy"", ""application_ver...","{""access_strategy"": ""shared"", ""allow_growth"": ..."

### TFRecord por tamaño de transferencia

Permite distinguir, por ejemplo, 256 KiB y 1 MiB sin alterar `file_format=tfrecord`.

In [17]:
if 'transfer_size_label' in df.columns:
    display(df[df['file_format'] == 'tfrecord'][[
        'experiment_id','job_id','file_format','batch_size',
        'transfer_size_bytes','transfer_size_label','metadata_status'
    ]])

Empty DataFrame
Columns: [experiment_id, job_id, file_format, batch_size, transfer_size_bytes, transfer_size_label, metadata_status]
Index: []

### HDF5: parámetros comunes del formato

DeepTuneIO v12 normaliza, cuando están disponibles, los parámetros HDF5 comunes entre aplicaciones:

- `chunking_enabled`
- `chunk_size_bytes`
- `compression_type`
- `compression_level`

En DLIO v1 se obtienen de `-ec`, `-cs`, `-co` y `-cl`. En DLIO 2.x/current se obtienen de la configuración YAML/Hydra equivalente. Los parámetros originales permanecen además en `application_parameters`.

## 11. Separación entre experimentos validados e incompletos

El CSV principal contiene únicamente experimentos con `PASS / COMPLETE / PASS`. Las demás ejecuciones se conservan en un CSV separado y en el JSON maestro.

In [18]:
validated_df = pd.read_csv(outputs['csv'])
incomplete_df = pd.read_csv(outputs['incomplete_csv'])

print('Experimentos validados:', len(validated_df))
print('Ejecuciones incompletas/no validadas:', len(incomplete_df))

Experimentos validados: 39
Ejecuciones incompletas/no validadas: 0

### Experimentos validados

In [19]:
validated_df[[
    'experiment_id','job_id','application','application_version',
    'file_format','batch_size','number_files','samples_per_file',
    'record_length_bytes','transfer_size_label',
    'nodes','processes','execution_status',
    'instrumentation_status','metadata_status'
]]

,experiment_id,job_id,application,application_version,file_format,batch_size,number_files,samples_per_file,record_length_bytes,transfer_size_label,nodes,processes,execution_status,instrumentation_status,metadata_status
0,DTIO_4935078,4935078,DeepGalaxy,legacy,hdf5,4,NaN,NaN,NaN,NaN,1,4,PASS,COMPLETE,PASS
1,DTIO_4969259,4969259,DeepGalaxy,legacy,hdf5,4,NaN,NaN,NaN,NaN,1,4,PASS,COMPLETE,PASS
2,DTIO_4998171,4998171,DeepGalaxy,legacy,hdf5,4,NaN,NaN,NaN,NaN,2,8,PASS,COMPLETE,PASS
3,DTIO_5004132,5004132,DeepGalaxy,legacy,hdf5,4,NaN,NaN,NaN,NaN,4,16,PASS,COMPLETE,PASS
4,DTIO_5005753,5005753,DeepGalaxy,legacy,hdf5,4,NaN,NaN,NaN,NaN,8,32,PASS,COMPLETE,PASS
5,DTIO_5006747,5006747,DeepGalaxy,legacy,hdf5,4,NaN,NaN,NaN,NaN,12,48,PASS,COMPLETE,PASS
6,DTIO_5136097,5136097,DeepGalaxy,legacy,hdf5,4,NaN,NaN,NaN,NaN,2,8,PASS,COMPLETE,PASS
7,DTIO_5145754,5145754,DeepGalaxy,legacy,hdf5,4,NaN,NaN,NaN,NaN,2,8,PASS,COMPLETE,PASS
8,DTIO_5147852,5147852,DeepGalaxy,legacy,hdf5,4,NaN,NaN,NaN,NaN,2,8,PASS,COMPLETE,PASS
9,DTIO_5164453,5164453,DeepGalaxy,legacy,hdf5,4,NaN,NaN,NaN,NaN,2,8,PASS,COMPLETE,PASS
10,DTIO_5171929,5171929,DeepGalaxy,legacy,hdf5,4,NaN,NaN,NaN,NaN,12,48,PASS,COMPLETE,PASS
11,DTIO_5172393,5172393,DeepGalaxy,legacy,hdf5,4,NaN,NaN,NaN,NaN,12,48,PASS,COMPLETE,PASS
12,DTIO_5173520,5173520,DeepGalaxy,legacy,hdf5,4,NaN,NaN,NaN,NaN,12,48,PASS,COMPLETE,PASS
13,DTIO_5178759,5178759,DeepGalaxy,legacy,hdf5,4,NaN,NaN,NaN,NaN,8,32,PASS,COMPLETE,PASS
14,DTIO_5181608,5181608,DeepGalaxy,legacy,hdf5,4,NaN,NaN,NaN,NaN,8,32,PASS,COMPLETE,PASS
15,DTIO_5182586,5182586,DeepGalaxy,legacy,hdf5,4,NaN,NaN,NaN,NaN,8,32,PASS,COMPLETE,PASS
16,DTIO_5183430,5183430,DeepGalaxy,legacy,hdf5,4,NaN,NaN,NaN,NaN,8,32,PASS,COMPLETE,PASS
17,DTIO_5184753,5184753,DeepGalaxy,legacy,hdf5,4,NaN,NaN,NaN,NaN,4,16,PASS,COMPLETE,PASS
18,DTIO_5185397,5185397,DeepGalaxy,legacy,hdf5,4,NaN,NaN,NaN,NaN,4,16,PASS,COMPLETE,PASS
19,DTIO_5186976,5186976,DeepGalaxy,legacy,hdf5,4,NaN,NaN,NaN,NaN,1,4,PASS,COMPLETE,PASS
20,DTIO_5189973,5189973,DeepGalaxy,legacy,hdf5,4,NaN,NaN,NaN,NaN,4,16,PASS,COMPLETE,PASS
21,DTIO_5196039,5196039,DeepGalaxy,legacy,hdf5,4,NaN,NaN,NaN,NaN,1,4,PASS,COMPLETE,PASS
22,DTIO_5317272,5317272,DeepGalaxy,legacy,hdf5,4,NaN,NaN,NaN,NaN,1,4,PASS,COMPLETE,PASS
23,DTIO_5333215,5333215,DeepGalaxy,legacy,hdf5,4,NaN,NaN,NaN,NaN,16,64,PASS,COMPLETE,PASS
24,DTIO_5347797,5347797,DeepGalaxy,legacy,hdf5,4,NaN,NaN,NaN,NaN,12,48,PASS,COMPLETE,PASS
25,DTIO_5348184,5348184,DeepGalaxy,legacy,hdf5,4,NaN,NaN,NaN,NaN,8,32,PASS,COMPLETE,PASS
26,DTIO_5349515,5349515,DeepGalaxy,legacy,hdf5,4,NaN,NaN,NaN,NaN,8,32,PASS,COMPLETE,PASS
27,DTIO_5350177,5350177,DeepGalaxy,legacy,hdf5,4,NaN,NaN,NaN,NaN,1,4,PASS,COMPLETE,PASS
28,DTIO_5352783,5352783,DeepGalaxy,legacy,hdf5,4,NaN,NaN,NaN,NaN,2,8,PASS,COMPLETE,PASS
29,DTIO_5353861,5353861,DeepGalaxy,legacy,hdf5,4,NaN,NaN,NaN,NaN,2,8,PASS,COMPLETE,PASS
30,DTIO_5366451,5366451,DeepGalaxy,legacy,hdf5,4,NaN,NaN,NaN,NaN,16,64,PASS,COMPLETE,PASS
31,DTIO_5369484,5369484,DeepGalaxy,legacy,hdf5,4,NaN,NaN,NaN,NaN,16,64,PASS,COMPLETE,PASS
32,DTIO_8773752,8773752,DeepGalaxy,legacy,hdf5,4,NaN,NaN,NaN,NaN,4,16,PASS,COMPLETE,PASS
33,DTIO_8784568,8784568,DeepGalaxy,legacy,hdf5,4,NaN,NaN,NaN,NaN,4,16,PASS,COMPLETE,PASS
34,DTIO_8787065,8787065,DeepGalaxy,legacy,hdf5,4,NaN,NaN,NaN,NaN,16,64,PASS,COMPLETE,PASS
35,DTIO_8806303,8806303,DeepGalaxy,legacy,hdf5,4,NaN,NaN,NaN,NaN,16,64,PASS,COMPLETE,PASS
36,DTIO_8810008,8810008,DeepGalaxy,legacy,hdf5,4,NaN,NaN,NaN,NaN,4,16,PASS,COMPLETE,PASS
37,DTIO_8849686,8849686,DeepGalaxy,legacy,hdf5,4,NaN,NaN,NaN,NaN,12,48,PASS,COMPLETE,PASS
38,DTIO_8850850,8850850,DeepGalaxy,legacy,hdf5,4,NaN,NaN,NaN,NaN,8,32,PASS,COMPLETE,PASS

### Ejecuciones incompletas o no validadas

No se eliminan: se preservan para trazabilidad y pueden reclasificarse si se recuperan datos faltantes.

In [20]:
incomplete_df[[
    'experiment_id','job_id','application','file_format',
    'execution_status','instrumentation_status','metadata_status',
    'incomplete_reason','stdout_file','stderr_file'
]]

Empty DataFrame
Columns: [experiment_id, job_id, application, file_format, execution_status, instrumentation_status, metadata_status, incomplete_reason, stdout_file, stderr_file]
Index: []

## 12. Recuperación conservadora de metadatos de campaña

DeepTuneIO v12 puede completar metadatos faltantes en ejecuciones incompletas usando únicamente valores invariantes y no ambiguos observados en la misma campaña. Esta recuperación **no convierte** una ejecución incompleta en experimento validado.

In [21]:
master = json.loads(Path(outputs['json']).read_text(encoding='utf-8'))
recovered = [r for r in master['records'] if r.get('metadata_recovery')]

print('Ejecuciones con metadatos recuperados:', len(recovered))

pd.DataFrame(recovered)[[
    'experiment_id','job_id','application','application_version',
    'file_format','file_format_source','file_format_confidence',
    'batch_size','record_length_bytes',
    'transfer_size_bytes','transfer_size_label','metadata_recovery',
    'scientific_validation_status','incomplete_reason'
]] if recovered else pd.DataFrame()

Ejecuciones con metadatos recuperados: 0

Empty DataFrame
Columns: []
Index: []

## 13. Matriz experimental

DeepTuneIO v12 construye automáticamente una matriz de configuraciones a partir **solo de los experimentos validados**. Las ejecuciones con la misma configuración se agrupan como réplicas.

In [22]:
matrix_df = pd.read_csv(outputs['experiment_matrix'])
coverage = json.loads(Path(outputs['campaign_coverage']).read_text(encoding='utf-8'))

print('Experimentos validados:', coverage['validated_experiments'])
print('Configuraciones únicas:', coverage['unique_configurations'])
print('Configuraciones con réplicas:', coverage['replicated_configurations'])
matrix_df

Experimentos validados: 39
Configuraciones únicas: 12
Configuraciones con réplicas: 12

,configuration_id,application,application_version,file_format,nodes,processes,ppn,batch_size,number_files,samples_per_file,...,application_configuration_signature,dataset_configuration_signature,experiment_configuration_signature,replicate_count,experiment_ids,job_ids,runtime_s_mean,io_time_s_mean,bandwidth_mib_s_mean,iops_mean
0,CFG_0001,DeepGalaxy,legacy,hdf5,1,4,4,4,NaN,NaN,...,"{""access_strategy"": ""shared"", ""allow_growth"": ...","{""application"": ""DeepGalaxy"", ""application_ver...","{""access_strategy"": ""shared"", ""allow_growth"": ...",3,DTIO_4935078;DTIO_5196039;DTIO_5350177,4935078;5196039;5350177,26808.028333,11.212027,187.432005,25175.149399
1,CFG_0002,DeepGalaxy,legacy,hdf5,1,4,4,4,NaN,NaN,...,"{""access_strategy"": ""shared_reload_shuffle"", ""...","{""application"": ""DeepGalaxy"", ""application_ver...","{""access_strategy"": ""shared_reload_shuffle"", ""...",3,DTIO_4969259;DTIO_5186976;DTIO_5317272,4969259;5186976;5317272,27959.109533,30.128272,523.429290,8814.680312
2,CFG_0003,DeepGalaxy,legacy,hdf5,12,48,4,4,NaN,NaN,...,"{""access_strategy"": ""shared_reload_shuffle"", ""...","{""application"": ""DeepGalaxy"", ""application_ver...","{""access_strategy"": ""shared_reload_shuffle"", ""...",3,DTIO_5006747;DTIO_5173520;DTIO_5347797,5006747;5173520;5347797,3168.795767,16.521763,8338.051780,170114.580400
3,CFG_0004,DeepGalaxy,legacy,hdf5,12,48,4,4,NaN,NaN,...,"{""access_strategy"": ""shared"", ""allow_growth"": ...","{""application"": ""DeepGalaxy"", ""application_ver...","{""access_strategy"": ""shared"", ""allow_growth"": ...",3,DTIO_5171929;DTIO_5172393;DTIO_8849686,5171929;5172393;8849686,3291.244967,5.266927,417.787239,119185.423377
4,CFG_0005,DeepGalaxy,legacy,hdf5,16,64,4,4,NaN,NaN,...,"{""access_strategy"": ""shared"", ""allow_growth"": ...","{""application"": ""DeepGalaxy"", ""application_ver...","{""access_strategy"": ""shared"", ""allow_growth"": ...",3,DTIO_5333215;DTIO_8787065;DTIO_8806303,5333215;8787065;8806303,2792.903667,5.795052,400.501885,117389.903548
5,CFG_0006,DeepGalaxy,legacy,hdf5,16,64,4,4,NaN,NaN,...,"{""access_strategy"": ""shared_reload_shuffle"", ""...","{""application"": ""DeepGalaxy"", ""application_ver...","{""access_strategy"": ""shared_reload_shuffle"", ""...",2,DTIO_5366451;DTIO_5369484,5366451;5369484,2591.076000,16.355838,9827.040011,256435.646348
6,CFG_0007,DeepGalaxy,legacy,hdf5,2,8,4,4,NaN,NaN,...,"{""access_strategy"": ""shared"", ""allow_growth"": ...","{""application"": ""DeepGalaxy"", ""application_ver...","{""access_strategy"": ""shared"", ""allow_growth"": ...",4,DTIO_4998171;DTIO_5147852;DTIO_5164453;DTIO_53...,4998171;5147852;5164453;5352783,14529.803975,8.239657,243.770776,63265.440349
7,CFG_0008,DeepGalaxy,legacy,hdf5,2,8,4,4,NaN,NaN,...,"{""access_strategy"": ""shared_reload_shuffle"", ""...","{""application"": ""DeepGalaxy"", ""application_ver...","{""access_strategy"": ""shared_reload_shuffle"", ""...",3,DTIO_5136097;DTIO_5145754;DTIO_5353861,5136097;5145754;5353861,15971.697400,29.156890,1070.953256,18493.003794
8,CFG_0009,DeepGalaxy,legacy,hdf5,4,16,4,4,NaN,NaN,...,"{""access_strategy"": ""shared_reload_shuffle"", ""...","{""application"": ""DeepGalaxy"", ""application_ver...","{""access_strategy"": ""shared_reload_shuffle"", ""...",4,DTIO_5004132;DTIO_5185397;DTIO_5189973;DTIO_87...,5004132;5185397;5189973;8773752,7400.496300,24.110563,2663.606748,45533.232064
9,CFG_0010,DeepGalaxy,legacy,hdf5,4,16,4,4,NaN,NaN,...,"{""access_strategy"": ""shared"", ""allow_growth"": ...","{""application"": ""DeepGalaxy"", ""application_ver...","{""access_strategy"": ""shared"", ""allow_growth"": ...",3,DTIO_5184753;DTIO_8784568;DTIO_8810008,5184753;8784568;8810008,7159.264033,6.284354,322.934486,85592.891051
10,CFG_0011,DeepGalaxy,legacy,hdf5,8,32,4,4,NaN,NaN,...,"{""access_strategy"": ""shared_reload_shuffle"", ""...","{""application"": ""DeepGalaxy"", ""application_ver...","{""access_strategy"": ""shared_reload_shuffle"", ""...",4,DTIO_5005753;DTIO_5182586;DTIO_5183430;DTIO_53...,5005753;5182586;5183430;5348184,4846.873100,21.771439,5158.580984,99281.943180
11,CFG_0012,DeepGalaxy,legacy,hdf5,8,32,4,4,NaN,NaN,...,"{""access_strategy"": ""shared"", ""allow_growth"": ...","{""application"": ""DeepGalaxy"", ""application_ver...","{""access_strategy"": ""shared"", ""allow_growth"": ...",4,DTIO_5178759;DTIO_5181608;DTIO_5349515;DTIO_88...,5178759;5181608;5349515;8850850,4474.726350,5.826076,366.496327,100783.858409

### Réplicas detectadas

Una réplica comparte la misma configuración normalizada: aplicación, formato, escala, batch size, sistema de archivos, striping y parámetros comunes del formato.

In [23]:
matrix_df[matrix_df['replicate_count'] > 1][[
    'configuration_id','application','application_version',
    'file_format','nodes','processes','ppn','batch_size',
    'number_files','samples_per_file','record_length_bytes',
    'transfer_size_bytes','chunking_enabled','chunk_size_bytes',
    'compression_type','compression_level',
    'stripe_count','replicate_count','job_ids'
]]

,configuration_id,application,application_version,file_format,nodes,processes,ppn,batch_size,number_files,samples_per_file,record_length_bytes,transfer_size_bytes,chunking_enabled,chunk_size_bytes,compression_type,compression_level,stripe_count,replicate_count,job_ids
0,CFG_0001,DeepGalaxy,legacy,hdf5,1,4,4,4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,3,4935078;5196039;5350177
1,CFG_0002,DeepGalaxy,legacy,hdf5,1,4,4,4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,3,4969259;5186976;5317272
2,CFG_0003,DeepGalaxy,legacy,hdf5,12,48,4,4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,3,5006747;5173520;5347797
3,CFG_0004,DeepGalaxy,legacy,hdf5,12,48,4,4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,3,5171929;5172393;8849686
4,CFG_0005,DeepGalaxy,legacy,hdf5,16,64,4,4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,3,5333215;8787065;8806303
5,CFG_0006,DeepGalaxy,legacy,hdf5,16,64,4,4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,2,5366451;5369484
6,CFG_0007,DeepGalaxy,legacy,hdf5,2,8,4,4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,4,4998171;5147852;5164453;5352783
7,CFG_0008,DeepGalaxy,legacy,hdf5,2,8,4,4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,3,5136097;5145754;5353861
8,CFG_0009,DeepGalaxy,legacy,hdf5,4,16,4,4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,4,5004132;5185397;5189973;8773752
9,CFG_0010,DeepGalaxy,legacy,hdf5,4,16,4,4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,3,5184753;8784568;8810008
10,CFG_0011,DeepGalaxy,legacy,hdf5,8,32,4,4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,4,5005753;5182586;5183430;5348184
11,CFG_0012,DeepGalaxy,legacy,hdf5,8,32,4,4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,4,5178759;5181608;5349515;8850850

### Cobertura de campaña

DeepTuneIO v12 no inventa configuraciones faltantes suponiendo un diseño factorial. El JSON de cobertura registra los valores observados; los huecos reales se determinarán cuando se proporcione o construya el diseño experimental esperado.

In [ ]:
coverage

## 14. Configuración reproducible del dataset

`number_files` y `samples_per_file` forman parte de la clave de configuración reproducible. Dos ejecuciones solo se consideran réplicas si coinciden también estos parámetros, junto con la versión de la aplicación, la configuración de paralelismo, almacenamiento y los parámetros normalizados del formato.

DeepTuneIO conserva además `application_parameters`, `normalized_parameters`, `configuration_parameters` y `configuration_signature`, por lo que los parámetros no normalizados o propios de una aplicación no se pierden.

In [24]:
matrix_df[[
    'configuration_id','application','application_version','file_format',
    'nodes','processes','ppn','batch_size',
    'number_files','samples_per_file','record_length_bytes',
    'transfer_size_bytes','chunking_enabled','chunk_size_bytes',
    'compression_type','compression_level',
    'filesystem','stripe_size_bytes','stripe_count',
    'application_configuration_signature','dataset_configuration_signature','experiment_configuration_signature','replicate_count','job_ids'
]]

,configuration_id,application,application_version,file_format,nodes,processes,ppn,batch_size,number_files,samples_per_file,...,compression_type,compression_level,filesystem,stripe_size_bytes,stripe_count,application_configuration_signature,dataset_configuration_signature,experiment_configuration_signature,replicate_count,job_ids
0,CFG_0001,DeepGalaxy,legacy,hdf5,1,4,4,4,NaN,NaN,...,NaN,NaN,lustre,1048576,1,"{""access_strategy"": ""shared"", ""allow_growth"": ...","{""application"": ""DeepGalaxy"", ""application_ver...","{""access_strategy"": ""shared"", ""allow_growth"": ...",3,4935078;5196039;5350177
1,CFG_0002,DeepGalaxy,legacy,hdf5,1,4,4,4,NaN,NaN,...,NaN,NaN,lustre,1048576,1,"{""access_strategy"": ""shared_reload_shuffle"", ""...","{""application"": ""DeepGalaxy"", ""application_ver...","{""access_strategy"": ""shared_reload_shuffle"", ""...",3,4969259;5186976;5317272
2,CFG_0003,DeepGalaxy,legacy,hdf5,12,48,4,4,NaN,NaN,...,NaN,NaN,lustre,1048576,1,"{""access_strategy"": ""shared_reload_shuffle"", ""...","{""application"": ""DeepGalaxy"", ""application_ver...","{""access_strategy"": ""shared_reload_shuffle"", ""...",3,5006747;5173520;5347797
3,CFG_0004,DeepGalaxy,legacy,hdf5,12,48,4,4,NaN,NaN,...,NaN,NaN,lustre,1048576,1,"{""access_strategy"": ""shared"", ""allow_growth"": ...","{""application"": ""DeepGalaxy"", ""application_ver...","{""access_strategy"": ""shared"", ""allow_growth"": ...",3,5171929;5172393;8849686
4,CFG_0005,DeepGalaxy,legacy,hdf5,16,64,4,4,NaN,NaN,...,NaN,NaN,lustre,1048576,1,"{""access_strategy"": ""shared"", ""allow_growth"": ...","{""application"": ""DeepGalaxy"", ""application_ver...","{""access_strategy"": ""shared"", ""allow_growth"": ...",3,5333215;8787065;8806303
5,CFG_0006,DeepGalaxy,legacy,hdf5,16,64,4,4,NaN,NaN,...,NaN,NaN,lustre,1048576,1,"{""access_strategy"": ""shared_reload_shuffle"", ""...","{""application"": ""DeepGalaxy"", ""application_ver...","{""access_strategy"": ""shared_reload_shuffle"", ""...",2,5366451;5369484
6,CFG_0007,DeepGalaxy,legacy,hdf5,2,8,4,4,NaN,NaN,...,NaN,NaN,lustre,1048576,1,"{""access_strategy"": ""shared"", ""allow_growth"": ...","{""application"": ""DeepGalaxy"", ""application_ver...","{""access_strategy"": ""shared"", ""allow_growth"": ...",4,4998171;5147852;5164453;5352783
7,CFG_0008,DeepGalaxy,legacy,hdf5,2,8,4,4,NaN,NaN,...,NaN,NaN,lustre,1048576,1,"{""access_strategy"": ""shared_reload_shuffle"", ""...","{""application"": ""DeepGalaxy"", ""application_ver...","{""access_strategy"": ""shared_reload_shuffle"", ""...",3,5136097;5145754;5353861
8,CFG_0009,DeepGalaxy,legacy,hdf5,4,16,4,4,NaN,NaN,...,NaN,NaN,lustre,1048576,1,"{""access_strategy"": ""shared_reload_shuffle"", ""...","{""application"": ""DeepGalaxy"", ""application_ver...","{""access_strategy"": ""shared_reload_shuffle"", ""...",4,5004132;5185397;5189973;8773752
9,CFG_0010,DeepGalaxy,legacy,hdf5,4,16,4,4,NaN,NaN,...,NaN,NaN,lustre,1048576,1,"{""access_strategy"": ""shared"", ""allow_growth"": ...","{""application"": ""DeepGalaxy"", ""application_ver...","{""access_strategy"": ""shared"", ""allow_growth"": ...",3,5184753;8784568;8810008
10,CFG_0011,DeepGalaxy,legacy,hdf5,8,32,4,4,NaN,NaN,...,NaN,NaN,lustre,1048576,1,"{""access_strategy"": ""shared_reload_shuffle"", ""...","{""application"": ""DeepGalaxy"", ""application_ver...","{""access_strategy"": ""shared_reload_shuffle"", ""...",4,5005753;5182586;5183430;5348184
11,CFG_0012,DeepGalaxy,legacy,hdf5,8,32,4,4,NaN,NaN,...,NaN,NaN,lustre,1048576,1,"{""access_strategy"": ""shared"", ""allow_growth"": ...","{""application"": ""DeepGalaxy"", ""application_ver...","{""access_strategy"": ""shared"", ""allow_growth"": ...",4,5178759;5181608;5349515;8850850

## 15. Detección automática de aplicación y versión

DeepTuneIO v12 utiliza adaptadores separados por aplicación y versión. La identidad se determina mediante evidencias del comando, configuración y metadatos disponibles; no se fuerza una versión cuando la evidencia es insuficiente.

In [25]:
df.groupby([
    'application','application_version',
    'application_version_source','application_version_confidence'
], dropna=False).size().reset_index(name='executions')

,application,application_version,application_version_source,application_version_confidence,executions
0,DeepGalaxy,legacy,dg_train_cli_signature,HIGH,39

### Parámetros originales y normalizados

Esto permite verificar que el adaptador de la aplicación no elimina parámetros específicos de la versión.

In [26]:
df[[
    'experiment_id','job_id','application','application_version',
    'application_parameters','normalized_parameters',
    'configuration_parameters','parameter_roles','derived_parameters','application_configuration_signature','dataset_configuration_signature','experiment_configuration_signature'
]].head()

,experiment_id,job_id,application,application_version,application_parameters,normalized_parameters,configuration_parameters,parameter_roles,derived_parameters,application_configuration_signature,dataset_configuration_signature,experiment_configuration_signature
0,DTIO_4935078,4935078,DeepGalaxy,legacy,"{""data_loading_mode"": 0, ""datasets_pattern"": ""...","{""access_strategy"": ""shared"", ""allow_growth"": ...","{""access_strategy"": ""shared"", ""allow_growth"": ...","{""access_strategy"": [""APPLICATION""], ""allow_gr...",{},"{""access_strategy"": ""shared"", ""allow_growth"": ...","{""application"": ""DeepGalaxy"", ""application_ver...","{""access_strategy"": ""shared"", ""allow_growth"": ..."
1,DTIO_4969259,4969259,DeepGalaxy,legacy,"{""data_loading_mode"": 1, ""datasets_pattern"": ""...","{""access_strategy"": ""shared_reload_shuffle"", ""...","{""access_strategy"": ""shared_reload_shuffle"", ""...","{""access_strategy"": [""APPLICATION""], ""allow_gr...",{},"{""access_strategy"": ""shared_reload_shuffle"", ""...","{""application"": ""DeepGalaxy"", ""application_ver...","{""access_strategy"": ""shared_reload_shuffle"", ""..."
2,DTIO_4998171,4998171,DeepGalaxy,legacy,"{""data_loading_mode"": 0, ""datasets_pattern"": ""...","{""access_strategy"": ""shared"", ""allow_growth"": ...","{""access_strategy"": ""shared"", ""allow_growth"": ...","{""access_strategy"": [""APPLICATION""], ""allow_gr...",{},"{""access_strategy"": ""shared"", ""allow_growth"": ...","{""application"": ""DeepGalaxy"", ""application_ver...","{""access_strategy"": ""shared"", ""allow_growth"": ..."
3,DTIO_5004132,5004132,DeepGalaxy,legacy,"{""data_loading_mode"": 1, ""datasets_pattern"": ""...","{""access_strategy"": ""shared_reload_shuffle"", ""...","{""access_strategy"": ""shared_reload_shuffle"", ""...","{""access_strategy"": [""APPLICATION""], ""allow_gr...",{},"{""access_strategy"": ""shared_reload_shuffle"", ""...","{""application"": ""DeepGalaxy"", ""application_ver...","{""access_strategy"": ""shared_reload_shuffle"", ""..."
4,DTIO_5005753,5005753,DeepGalaxy,legacy,"{""data_loading_mode"": 1, ""datasets_pattern"": ""...","{""access_strategy"": ""shared_reload_shuffle"", ""...","{""access_strategy"": ""shared_reload_shuffle"", ""...","{""access_strategy"": [""APPLICATION""], ""allow_gr...",{},"{""access_strategy"": ""shared_reload_shuffle"", ""...","{""application"": ""DeepGalaxy"", ""application_ver...","{""access_strategy"": ""shared_reload_shuffle"", ""..."

## 16. Firmas de configuración

`application_configuration_signature` representa únicamente la configuración propia de la aplicación y su versión. `experiment_configuration_signature` añade escala de ejecución y almacenamiento (`nodes`, `processes`, `ppn`, `filesystem`, `stripe_size_bytes`, `stripe_count`, `operation_mode`). La segunda es la firma reproducible completa.

In [27]:
matrix_df[[
    'configuration_id','nodes','processes','ppn','stripe_count',
    'application_configuration_signature','experiment_configuration_signature',
    'replicate_count','job_ids'
]]

,configuration_id,nodes,processes,ppn,stripe_count,application_configuration_signature,experiment_configuration_signature,replicate_count,job_ids
0,CFG_0001,1,4,4,1,"{""access_strategy"": ""shared"", ""allow_growth"": ...","{""access_strategy"": ""shared"", ""allow_growth"": ...",3,4935078;5196039;5350177
1,CFG_0002,1,4,4,1,"{""access_strategy"": ""shared_reload_shuffle"", ""...","{""access_strategy"": ""shared_reload_shuffle"", ""...",3,4969259;5186976;5317272
2,CFG_0003,12,48,4,1,"{""access_strategy"": ""shared_reload_shuffle"", ""...","{""access_strategy"": ""shared_reload_shuffle"", ""...",3,5006747;5173520;5347797
3,CFG_0004,12,48,4,1,"{""access_strategy"": ""shared"", ""allow_growth"": ...","{""access_strategy"": ""shared"", ""allow_growth"": ...",3,5171929;5172393;8849686
4,CFG_0005,16,64,4,1,"{""access_strategy"": ""shared"", ""allow_growth"": ...","{""access_strategy"": ""shared"", ""allow_growth"": ...",3,5333215;8787065;8806303
5,CFG_0006,16,64,4,1,"{""access_strategy"": ""shared_reload_shuffle"", ""...","{""access_strategy"": ""shared_reload_shuffle"", ""...",2,5366451;5369484
6,CFG_0007,2,8,4,1,"{""access_strategy"": ""shared"", ""allow_growth"": ...","{""access_strategy"": ""shared"", ""allow_growth"": ...",4,4998171;5147852;5164453;5352783
7,CFG_0008,2,8,4,1,"{""access_strategy"": ""shared_reload_shuffle"", ""...","{""access_strategy"": ""shared_reload_shuffle"", ""...",3,5136097;5145754;5353861
8,CFG_0009,4,16,4,1,"{""access_strategy"": ""shared_reload_shuffle"", ""...","{""access_strategy"": ""shared_reload_shuffle"", ""...",4,5004132;5185397;5189973;8773752
9,CFG_0010,4,16,4,1,"{""access_strategy"": ""shared"", ""allow_growth"": ...","{""access_strategy"": ""shared"", ""allow_growth"": ...",3,5184753;8784568;8810008
10,CFG_0011,8,32,4,1,"{""access_strategy"": ""shared_reload_shuffle"", ""...","{""access_strategy"": ""shared_reload_shuffle"", ""...",4,5005753;5182586;5183430;5348184
11,CFG_0012,8,32,4,1,"{""access_strategy"": ""shared"", ""allow_growth"": ...","{""access_strategy"": ""shared"", ""allow_growth"": ...",4,5178759;5181608;5349515;8850850

## 17. Validación semántica de parámetros y firmas

La configuración se separa ahora en tres niveles: aplicación lógica, dataset lógico y experimento reproducible completo. `number_files` y `samples_per_file` se conservan siempre para reproducibilidad, pero DLIO puede marcarlos como `SCALING`; en ese caso no fragmentan la firma lógica del dataset. `total_samples` se deriva únicamente cuando ambos valores están observados.

In [28]:
print('Firmas aplicación:', validated_df['application_configuration_signature'].nunique())
print('Firmas dataset:', validated_df['dataset_configuration_signature'].nunique())
print('Firmas experimento:', validated_df['experiment_configuration_signature'].nunique())

validated_df[[
    'experiment_id','nodes','processes','number_files','samples_per_file',
    'parameter_roles','derived_parameters',
    'application_configuration_signature','dataset_configuration_signature',
    'experiment_configuration_signature'
]].head()

Firmas aplicación: 2
Firmas dataset: 1
Firmas experimento: 12

,experiment_id,nodes,processes,number_files,samples_per_file,parameter_roles,derived_parameters,application_configuration_signature,dataset_configuration_signature,experiment_configuration_signature
0,DTIO_4935078,1,4,NaN,NaN,"{""access_strategy"": [""APPLICATION""], ""allow_gr...",{},"{""access_strategy"": ""shared"", ""allow_growth"": ...","{""application"": ""DeepGalaxy"", ""application_ver...","{""access_strategy"": ""shared"", ""allow_growth"": ..."
1,DTIO_4969259,1,4,NaN,NaN,"{""access_strategy"": [""APPLICATION""], ""allow_gr...",{},"{""access_strategy"": ""shared_reload_shuffle"", ""...","{""application"": ""DeepGalaxy"", ""application_ver...","{""access_strategy"": ""shared_reload_shuffle"", ""..."
2,DTIO_4998171,2,8,NaN,NaN,"{""access_strategy"": [""APPLICATION""], ""allow_gr...",{},"{""access_strategy"": ""shared"", ""allow_growth"": ...","{""application"": ""DeepGalaxy"", ""application_ver...","{""access_strategy"": ""shared"", ""allow_growth"": ..."
3,DTIO_5004132,4,16,NaN,NaN,"{""access_strategy"": [""APPLICATION""], ""allow_gr...",{},"{""access_strategy"": ""shared_reload_shuffle"", ""...","{""application"": ""DeepGalaxy"", ""application_ver...","{""access_strategy"": ""shared_reload_shuffle"", ""..."
4,DTIO_5005753,8,32,NaN,NaN,"{""access_strategy"": [""APPLICATION""], ""allow_gr...",{},"{""access_strategy"": ""shared_reload_shuffle"", ""...","{""application"": ""DeepGalaxy"", ""application_ver...","{""access_strategy"": ""shared_reload_shuffle"", ""..."

## 18. Parámetros efectivos y valores por defecto de DLIO v1

El adaptador distingue ahora entre parámetros presentes explícitamente en `# exe:` y valores por defecto conocidos de DLIO v1. Los defaults se incorporan a `normalized_parameters` y a las firmas reproducibles, pero su procedencia queda registrada en `parameter_provenance`. Una lista de opciones permitidas no se interpreta automáticamente como valor por defecto.

In [29]:
validated_df[[
    'experiment_id','application','application_version','file_format',
    'application_parameters','normalized_parameters','parameter_provenance'
]].head()

,experiment_id,application,application_version,file_format,application_parameters,normalized_parameters,parameter_provenance
0,DTIO_4935078,DeepGalaxy,legacy,hdf5,"{""data_loading_mode"": 0, ""datasets_pattern"": ""...","{""access_strategy"": ""shared"", ""allow_growth"": ...","{""access_strategy"": {""confidence"": ""HIGH"", ""so..."
1,DTIO_4969259,DeepGalaxy,legacy,hdf5,"{""data_loading_mode"": 1, ""datasets_pattern"": ""...","{""access_strategy"": ""shared_reload_shuffle"", ""...","{""access_strategy"": {""confidence"": ""HIGH"", ""so..."
2,DTIO_4998171,DeepGalaxy,legacy,hdf5,"{""data_loading_mode"": 0, ""datasets_pattern"": ""...","{""access_strategy"": ""shared"", ""allow_growth"": ...","{""access_strategy"": {""confidence"": ""HIGH"", ""so..."
3,DTIO_5004132,DeepGalaxy,legacy,hdf5,"{""data_loading_mode"": 1, ""datasets_pattern"": ""...","{""access_strategy"": ""shared_reload_shuffle"", ""...","{""access_strategy"": {""confidence"": ""HIGH"", ""so..."
4,DTIO_5005753,DeepGalaxy,legacy,hdf5,"{""data_loading_mode"": 1, ""datasets_pattern"": ""...","{""access_strategy"": ""shared_reload_shuffle"", ""...","{""access_strategy"": {""confidence"": ""HIGH"", ""so..."